# Notebook 01 - PreEDA: Vietnam Student Dataset

Notebook này thực hiện bước Preliminary Exploratory Data Analysis (PreEDA) trên bộ dữ liệu khảo sát sinh viên Việt Nam nhằm đánh giá tổng quan về cấu trúc, chất lượng và đặc điểm ban đầu của dữ liệu.

Giai đoạn PreEDA được thực hiện trước bước Cleaning & Preprocessing nhằm xác định các vấn đề tiềm ẩn trong dữ liệu như giá trị thiếu, dữ liệu trùng lặp, kiểu dữ liệu không phù hợp và các đặc điểm phân bố ban đầu.

Notebook được xây dựng dựa trên cùng quy trình với Notebook 01 của bộ dữ liệu quốc tế nhằm đảm bảo tính nhất quán trong pipeline nghiên cứu Digital Burnout và tạo cơ sở cho việc so sánh giữa hai bộ dữ liệu.

# 0. Set Up

Thiết lập môi trường phân tích cần thiết cho quá trình PreEDA.

In [1]:
# Import các thư viện phục vụ phân tích dữ liệu

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import os


# Thiết lập hiển thị dữ liệu

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)


# Thiết lập cấu hình biểu đồ

sns.set_theme(style="whitegrid")

In [2]:
# Thiết lập đường dẫn tương đối đến bộ dữ liệu khảo sát sinh viên Việt Nam

data_path = os.path.join(
    "..",
    "..",
    "data",
    "raw",
    "vietnam_dataset",
    "vn_digital_burnout.csv"
)

print("Đã thiết lập đường dẫn dữ liệu.")

Đã thiết lập đường dẫn dữ liệu.

In [3]:
# Kiểm tra sự tồn tại của file dữ liệu đầu vào

if os.path.exists(data_path):
    print("Đã tìm thấy bộ dữ liệu.")
else:
    print("Không tìm thấy bộ dữ liệu. Vui lòng kiểm tra lại đường dẫn.")

Đã tìm thấy bộ dữ liệu.

# 1. Load Dataset

Đọc bộ dữ liệu khảo sát sinh viên Việt Nam từ file CSV và kiểm tra dữ liệu đầu vào trước khi thực hiện các bước phân tích tổng quan.

Giai đoạn này chỉ thực hiện tải dữ liệu và quan sát ban đầu. Không thực hiện bất kỳ thao tác thay đổi hoặc xử lý dữ liệu.

In [4]:
# Đọc bộ dữ liệu khảo sát sinh viên Việt Nam

survey_dataset = pd.read_csv(data_path)

print("Đã tải dữ liệu thành công.")

Đã tải dữ liệu thành công.

In [5]:
# Kiểm tra kích thước bộ dữ liệu

dataset_shape = survey_dataset.shape

print("Kích thước bộ dữ liệu:")
print(f"Số dòng: {dataset_shape[0]}")
print(f"Số cột: {dataset_shape[1]}")

Kích thước bộ dữ liệu:
Số dòng: 641
Số cột: 25

In [6]:
# Hiển thị 5 dòng dữ liệu đầu tiên

survey_dataset.head()

,Giới tính của bạn?,Năm sinh?,Bạn đang ở giai đoạn nào?,Hình thức học tập / làm việc chính hiện tại:,Mô tả cách bạn dùng thiết bị số hiện tại:,Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?,"Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?","Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?",Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?,Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?,Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?,Con người cần hô hấp để sống đúng không?,"Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?",Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,"Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?","Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?","Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?","Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?",Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?,Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 9),Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,"Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.","Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.","Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống."
0,Nam,2006 - 2008,Sinh viên đại học / cao đẳng (năm 3-4+),Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,"Chủ yếu để giải trí (mạng xã hội, game, xem phim)",6-8 giờ,2-4 giờ,Trên 2 giờ/ngày,Hầu như mỗi tối,Dưới 30 thông báo/ngày,30-60 lần/ngày,Có,20-50 lần,1,Trên 10 lần (mình gần như bị ngắt liên tục),3-4 lần,Dưới 1 giờ,Trên 75% - hoàn thành tốt,5-6 tiếng,1,9,10,1,1,4
1,Nữ,2006 - 2008,Sinh viên đại học / cao đẳng (năm 1-2),"Kết hợp hybrid (2-3 ngày trực tiếp, còn lại on...",Cân bằng cả học lẫn giải trí,8-10 giờ,1-2 giờ,Dưới 30 phút/ngày,1-2 lần/tuần,30-80 thông báo/ngày,30-60 lần/ngày,Mình không biết,50-100 lần,6,3-5 lần,1-2 lần,1-2 giờ,Trên 75% - hoàn thành tốt,7-8 tiếng,9,9,9,5,5,4
2,Nữ,2006 - 2008,Sinh viên đại học / cao đẳng (năm 3-4+),Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,"Chủ yếu để học (LMS, tài liệu, nghiên cứu)",Trên 10 giờ,2-4 giờ,30 phút - 1 giờ/ngày,Hầu như mỗi tối,Trên 150 thông báo/ngày,60-100 lần/ngày,Có,Trên 100 lần,7,3-5 lần,5 lần trở lên,2-3 giờ,50-75%,7-8 tiếng,8,9,6,5,5,5
3,Nữ,2006 - 2008,Sinh viên đại học / cao đẳng (năm 1-2),"Tự do, không cố định lịch trình",Cân bằng cả học lẫn giải trí,8-10 giờ,2-4 giờ,Dưới 30 phút/ngày,Hầu như mỗi tối,30-80 thông báo/ngày,30-60 lần/ngày,Có,20-50 lần,6,3-5 lần,5 lần trở lên,1-2 giờ,Trên 75% - hoàn thành tốt,5-6 tiếng,4,9,8,4,5,3
4,Nữ,2009 - 2012,Học sinh THPT,Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,"Chủ yếu để giải trí (mạng xã hội, game, xem phim)",Trên 10 giờ,Trên 4 giờ,Trên 2 giờ/ngày,Hầu như mỗi tối,80-150 thông báo/ngày,30-60 lần/ngày,Có,20-50 lần,7,3-5 lần,3-4 lần,1-2 giờ,Dưới 25% - hầu như không làm được gì,7-8 tiếng,8,9,4,2,2,4

# 2. Dataset Overview

Phân tích tổng quan cấu trúc của bộ dữ liệu khảo sát sinh viên Việt Nam nhằm hiểu rõ các biến được thu thập và đặc điểm ban đầu của dataset.

In [7]:
# Hiển thị danh sách các biến trong bộ dữ liệu

dataset_columns = survey_dataset.columns.tolist()

print("Danh sách biến trong bộ dữ liệu:")

for column in dataset_columns:
    print(column)

Danh sách biến trong bộ dữ liệu:
Giới tính của bạn?
Năm sinh?
Bạn đang ở giai đoạn nào?
Hình thức học tập / làm việc chính hiện tại:
Mô tả cách bạn dùng thiết bị số hiện tại:
Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ  (gộp cả học/làm lẫn giải trí)?
Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?
Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?
Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?
Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?
Con người cần hô hấp để sống đúng không?
Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?
Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?
Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?
Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?
Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?
Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 9)
Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?
Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.
Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống.

In [8]:
# Kiểm tra kiểu dữ liệu của từng biến

data_types = survey_dataset.dtypes.to_frame()

data_types.columns = ["data_type"]

data_types

                                                   data_type
Giới tính của bạn?                                    object
Năm sinh?                                             object
Bạn đang ở giai đoạn nào?                             object
Hình thức học tập / làm việc chính hiện tại:          object
Mô tả cách bạn dùng thiết bị số hiện tại:             object
Trung bình mỗi ngày bạn dùng điện thoại và máy ...    object
Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội...    object
Bạn có thường xuyên cuộn feed (TikTok, Reels, S...    object
Bạn có thường dùng điện thoại hoặc máy tính sau...    object
Bạn nhận khoảng bao nhiêu thông báo trên tất cả...    object
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi...    object
Con người cần hô hấp để sống đúng không?              object
Trong một ngày học/làm việc, bạn chuyển qua lại...    object
Bạn tự đánh giá khả năng tập trung của mình dạo...     int64
Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điệ...    object
Trong một ngày, bạn có bao nhiêu lần ngồi học h...    object
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tậ...    object
Nhìn lại hôm qua, bạn hoàn thành được khoảng ba...    object
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (khô...    object
Dạo này bạn thấy giấc ngủ của mình như thế nào?...     int64
Bạn còn đang thực hiện khảo sát này đúng không?...     int64
Mức độ có động lực để học tập hoặc làm việc của...     int64
Mình cảm thấy bã người, kiệt sức chỉ vì phải li...     int64
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn...     int64
Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ...     int64

In [9]:
# Hiển thị thông tin tổng quan của bộ dữ liệu

survey_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 25 columns):
 #   Column                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                           --------------  -----
 0   Giới tính của bạn?                                                                                                                               641 non-null    object
 1   Năm sinh?                                                                                                                                        641 non-null    object
 2   Bạn đang ở giai đoạn nào?                                                                                                                        641 non-null    object
 3   Hình thức học tập / làm việc chính hiện tại:                                                                                                     641 non-null    object
 4   Mô tả cách bạn dùng thiết bị số hiện tại:                                                                                                        641 non-null    object
 5   Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ  (gộp cả học/làm lẫn giải trí)?                                      641 non-null    object
 6   Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?                                                641 non-null    object
 7   Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?                    641 non-null    object
 8   Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?                                                                                      641 non-null    object
 9   Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?                                                                               641 non-null    object
 10  Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?                                                                                            641 non-null    object
 11  Con người cần hô hấp để sống đúng không?                                                                                                         641 non-null    object
 12  Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?                                                          641 non-null    object
 13  Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?                                                                                   641 non-null    int64
 14  Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?                                                   641 non-null    object
 15  Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?                      641 non-null    object
 16  Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?               641 non-null    object
 17  Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?  641 non-null    object
 18  Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?                                                                                641 non-null    object
 19  Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?                                                     641 non-null    int64
 20  Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 9)                                                                    641 non-null    int64
 21  Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?                                                                           641 non-null    int64
 22  Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.              641 non-null    int64
 23  Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.                                   641 non-null    int64
 24  Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống.                                                   641 non-null    int64
dtypes: int64(7), object(18)
memory usage: 125.3+ KB

# 3. Data Quality Assessment

Đánh giá chất lượng dữ liệu ban đầu của bộ dữ liệu khảo sát sinh viên Việt Nam nhằm xác định các vấn đề tiềm ẩn trước khi thực hiện bước Cleaning & Preprocessing.

Phần này thực hiện đánh giá:

- Giá trị thiếu (Missing Values).
- Bản ghi trùng lặp (Duplicate Records).
- Số lượng giá trị duy nhất của từng biến (Unique Values).
- Thống kê mô tả dữ liệu (Descriptive Statistics).

Các kết quả thu được chỉ nhằm mục đích khảo sát và ghi nhận vấn đề.

## 3.1 Missing Values

Kiểm tra sự tồn tại của các giá trị thiếu trong từng biến nhằm đánh giá mức độ đầy đủ của dữ liệu khảo sát.

In [10]:
# Kiểm tra số lượng và tỷ lệ giá trị thiếu trong từng biến

missing_summary = survey_dataset.isnull().sum().to_frame()

missing_summary.columns = ["missing_count"]

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"]
    / len(survey_dataset)
) * 100


missing_summary = missing_summary.sort_values(
    by="missing_count",
    ascending=False
)

missing_summary

,missing_count,missing_percentage
Giới tính của bạn?,0,0.0
Năm sinh?,0,0.0
Bạn đang ở giai đoạn nào?,0,0.0
Hình thức học tập / làm việc chính hiện tại:,0,0.0
Mô tả cách bạn dùng thiết bị số hiện tại:,0,0.0
Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?,0,0.0
"Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?",0,0.0
"Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?",0,0.0
Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?,0,0.0
Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?,0,0.0
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?,0,0.0
Con người cần hô hấp để sống đúng không?,0,0.0
"Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?",0,0.0
Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,0,0.0
"Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?",0,0.0
"Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?",0,0.0
"Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?",0,0.0
"Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?",0,0.0
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?,0,0.0
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,0,0.0
Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 9),0,0.0
Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,0,0.0
"Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.",0,0.0
"Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.",0,0.0
"Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống.",0,0.0

## 3.2 Duplicate Records

Kiểm tra sự tồn tại của các bản ghi bị trùng lặp trong bộ dữ liệu khảo sát.

In [11]:
# Kiểm tra số lượng bản ghi trùng lặp

duplicate_records = survey_dataset.duplicated().sum()

print(f"Số lượng bản ghi trùng lặp: {duplicate_records}")

Số lượng bản ghi trùng lặp: 24

## 3.3 Unique Values

Kiểm tra số lượng giá trị duy nhất của từng biến nhằm hiểu rõ đặc điểm của các biến trong dataset.

In [12]:
# Kiểm tra số lượng giá trị duy nhất của từng biến

unique_values = survey_dataset.nunique().to_frame()

unique_values.columns = ["unique_count"]


unique_values = unique_values.sort_values(
    by="unique_count",
    ascending=True
)

unique_values

                                                    unique_count
Giới tính của bạn?                                             2
Con người cần hô hấp để sống đúng không?                       3
Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội...             4
Hình thức học tập / làm việc chính hiện tại:                   4
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi...             4
Bạn nhận khoảng bao nhiêu thông báo trên tất cả...             4
Bạn có thường dùng điện thoại hoặc máy tính sau...             4
Mô tả cách bạn dùng thiết bị số hiện tại:                      4
Trong một ngày học/làm việc, bạn chuyển qua lại...             4
Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điệ...             4
Trong một ngày, bạn có bao nhiêu lần ngồi học h...             4
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tậ...             4
Nhìn lại hôm qua, bạn hoàn thành được khoảng ba...             4
Bạn có thường xuyên cuộn feed (TikTok, Reels, S...             5
Năm sinh?                                                      5
Trung bình mỗi ngày bạn dùng điện thoại và máy ...             5
Mình cảm thấy bã người, kiệt sức chỉ vì phải li...             5
Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ...             5
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (khô...             5
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn...             5
Bạn đang ở giai đoạn nào?                                      7
Bạn còn đang thực hiện khảo sát này đúng không?...             9
Bạn tự đánh giá khả năng tập trung của mình dạo...            10
Dạo này bạn thấy giấc ngủ của mình như thế nào?...            10
Mức độ có động lực để học tập hoặc làm việc của...            10

## 3.4 Descriptive Statistics

Phân tích thống kê mô tả nhằm quan sát đặc điểm phân bố ban đầu của các biến trong dataset.

In [13]:
# Thống kê mô tả cho các biến số

numerical_statistics = survey_dataset.describe()

numerical_statistics

,Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 9),Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,"Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.","Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.","Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống."
count,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000
mean,5.469579,5.149766,8.736349,5.393136,3.574103,3.923557,3.597504
std,2.200020,2.037777,1.141848,2.167563,1.069996,1.127258,1.137538
min,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000
25%,4.000000,4.000000,9.000000,4.000000,3.000000,3.000000,3.000000
50%,6.000000,5.000000,9.000000,6.000000,4.000000,4.000000,4.000000
75%,7.000000,7.000000,9.000000,7.000000,4.000000,5.000000,4.000000
max,10.000000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000

In [14]:
# Thống kê mô tả cho các biến phân loại

categorical_statistics = survey_dataset.describe(
    include="object"
)

categorical_statistics

,Giới tính của bạn?,Năm sinh?,Bạn đang ở giai đoạn nào?,Hình thức học tập / làm việc chính hiện tại:,Mô tả cách bạn dùng thiết bị số hiện tại:,Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?,"Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?","Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?",Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?,Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?,Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?,Con người cần hô hấp để sống đúng không?,"Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?","Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?","Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?","Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?","Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?",Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?
count,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641,641
unique,2,5,7,4,4,5,4,5,4,4,4,3,4,4,4,4,4,5
top,Nữ,2003 - 2005,Sinh viên đại học / cao đẳng (năm 3-4+),Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,Cân bằng cả học lẫn giải trí,8-10 giờ,2-4 giờ,1-2 giờ/ngày,Hầu như mỗi tối,30-80 thông báo/ngày,30-60 lần/ngày,Có,20-50 lần,6-10 lần,3-4 lần,2-3 giờ,25-50%,5-6 tiếng
freq,406,231,231,455,446,238,256,192,529,232,288,620,263,236,272,208,216,208

# 4. Survey Indicator Overview

Khảo sát sơ bộ các nhóm chỉ báo (indicators) liên quan đến Digital Burnout và hiệu suất học tập trong bộ dữ liệu khảo sát sinh viên Việt Nam

Phần này tập trung phân tích các nhóm chỉ báo:

- Digital Exposure Indicators:
    - Thời gian sử dụng thiết bị số.
    - Thời gian sử dụng mạng xã hội.
    - Hành vi doomscrolling.
    - Sử dụng thiết bị vào ban đêm.
    - Notification và smartphone usage.


- Cognitive Performance Indicators:
    - Khả năng tập trung.
    - Mức độ phân tâm.
    - Focus sessions.
    - Deep work hours.
    - Task completion.


- Sleep & Recovery Indicators:
    - Thời lượng ngủ.
    - Chất lượng giấc ngủ.


- Burnout Symptom Indicators:
    - Emotional exhaustion.
    - Stress.
    - Mental fatigue.

## 4.1 Burnout Symptom Indicators

Kiểm tra các câu hỏi khảo sát liên quan đến biểu hiện Digital Burnout.
Các nhóm triệu chứng bao gồm:

- Emotional Exhaustion.
- Stress.
- Mental Fatigue.

In [15]:
# Xác định các biến liên quan đến burnout symptoms

burnout_indicator_keywords = [
    "bã người",
    "kiệt sức",
    "căng thẳng",
    "lo lắng",
    "đầu nặng",
    "mệt mỏi"
]


burnout_indicator_columns = []

for column in survey_dataset.columns:
    for keyword in burnout_indicator_keywords:
        if keyword.lower() in column.lower():
            burnout_indicator_columns.append(column)


print("Các biến liên quan đến burnout symptoms:")

for column in burnout_indicator_columns:
    print(column)

Các biến liên quan đến burnout symptoms:
Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.
Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.
Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống.
Mình cảm thấy đầu nặng, mệt mỏi và khó tắt não ngay cả khi đã tắt máy hay bỏ điện thoại xuống.

## 4.2 Productivity Indicators

Khảo sát các chỉ báo phản ánh hiệu suất học tập và khả năng duy trì sự tập trung của sinh viên.
Các nhóm chỉ báo:

- Concentration.
- Distraction.
- Focus sessions.
- Deep work.
- Task completion.
- Motivation.

In [16]:
# Xác định các biến liên quan đến productivity indicators

productivity_keywords = [
    "tập trung",
    "kéo ra",
    "liên tục",
    "hoàn thành",
    "động lực"
]


productivity_indicator_columns = []

for column in survey_dataset.columns:
    for keyword in productivity_keywords:
        if keyword.lower() in column.lower():
            productivity_indicator_columns.append(column)


print("Các biến liên quan đến productivity indicators:")

for column in productivity_indicator_columns:
    print(column)

Các biến liên quan đến productivity indicators:
Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?
Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?
Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?
Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?
Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?
Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?
Mình cảm thấy bã người, kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.

## 4.3 Digital Exposure & Sleep Indicators

Khảo sát các chỉ báo liên quan đến mức độ tiếp xúc với thiết bị số và khả năng phục hồi thông qua giấc ngủ của sinh viên.

Phần này xác định các nhóm câu hỏi liên quan đến:

- Digital Exposure:
    - Thời gian sử dụng thiết bị số.
    - Thời gian sử dụng mạng xã hội.
    - Hành vi doomscrolling.
    - Sử dụng thiết bị sau 22 giờ.
    - Số lượng thông báo.
    - Tần suất mở khóa thiết bị.
    - Tần suất chuyển đổi ứng dụng hoặc tab.

- Sleep & Recovery:
    - Thời lượng ngủ mỗi ngày.
    - Chất lượng giấc ngủ.

In [17]:
# Xác định các biến liên quan đến digital exposure và sleep indicators

digital_sleep_keywords = [
    "dùng điện thoại",
    "mạng xã hội",
    "cuộn feed",
    "sau 22 giờ",
    "thông báo",
    "mở khóa",
    "ứng dụng/tab",
    "ngủ",
    "giấc ngủ"
]


digital_sleep_indicator_columns = []

for column in survey_dataset.columns:
    for keyword in digital_sleep_keywords:
        if keyword.lower() in column.lower():
            digital_sleep_indicator_columns.append(column)


print("Các biến thuộc nhóm Digital Exposure và Sleep & Recovery:")

for column in digital_sleep_indicator_columns:
    print(column)

Các biến thuộc nhóm Digital Exposure và Sleep & Recovery:
Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ  (gộp cả học/làm lẫn giải trí)?
Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?
Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?
Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?
Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?
Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?
Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?
Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?
Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?
Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.

## 4.4 Context Variables

Khảo sát các biến bối cảnh cá nhân và môi trường học tập nhằm mô tả đặc điểm của nhóm sinh viên tham gia khảo sát.
Các nhóm biến bao gồm:

- Thông tin cá nhân:
    - Giới tính.
    - Năm sinh.

- Thông tin học tập:
    - Giai đoạn học tập hiện tại.
    - Hình thức học tập/làm việc.

- Bối cảnh sử dụng thiết bị:
    - Mục đích sử dụng thiết bị số.

In [18]:
# Xác định các biến thuộc nhóm context variables

context_keywords = [
    "Giới tính",
    "Năm sinh",
    "giai đoạn",
    "Hình thức",
    "Mô tả cách"
]


context_columns = []

for column in survey_dataset.columns:
    for keyword in context_keywords:
        if keyword.lower() in column.lower():
            context_columns.append(column)


print("Các biến thuộc nhóm Context Variables:")

for column in context_columns:
    print(column)

Các biến thuộc nhóm Context Variables:
Giới tính của bạn?
Năm sinh?
Bạn đang ở giai đoạn nào?
Hình thức học tập / làm việc chính hiện tại:
Mô tả cách bạn dùng thiết bị số hiện tại:

## 4.5 Summary of Survey Indicators

Tổng hợp các nhóm chỉ báo được thu thập trong bộ dữ liệu khảo sát sinh viên Việt Nam nhằm đánh giá mức độ đầy đủ của dữ liệu phục vụ nghiên cứu Digital Burnout.

Các nhóm chỉ báo chính trong dataset bao gồm:

| Nhóm chỉ báo | Nội dung |
| --- | --- |
| Digital Exposure Indicators | Mức độ tiếp xúc với thiết bị số, mạng xã hội và hành vi sử dụng công nghệ |
| Cognitive Performance Indicators | Khả năng tập trung, mức độ phân tâm và hiệu suất học tập |
| Sleep & Recovery Indicators | Thời lượng ngủ và chất lượng giấc ngủ |
| Burnout Symptom Indicators | Các biểu hiện kiệt sức, căng thẳng và mệt mỏi tinh thần |
| Context Variables | Đặc điểm cá nhân và bối cảnh học tập/sử dụng thiết bị |


Bộ dữ liệu khảo sát sinh viên Việt Nam đã thu thập được các nhóm thông tin cần thiết cho nghiên cứu Digital Burnout.

Các nhóm biến bao phủ các khía cạnh chính:

- Mức độ tiếp xúc với công nghệ.
- Khả năng duy trì tập trung.
- Hiệu suất học tập.
- Chất lượng phục hồi.
- Các biểu hiện liên quan đến burnout.


Tuy nhiên, dữ liệu hiện vẫn đang ở dạng raw survey với:

- Tên biến dạng câu hỏi.
- Giá trị trả lời dạng văn bản.
- Chưa có cấu trúc feature chuẩn hóa.


Các bước chuẩn hóa dữ liệu sẽ được thực hiện trong Notebook 02 - Cleaning & Preprocessing.