# Notebook 01 - PreEDA: Vietnam Student Dataset

Notebook này thực hiện bước Preliminary Exploratory Data Analysis (PreEDA) trên bộ dữ liệu khảo sát sinh viên Việt Nam nhằm đánh giá tổng quan về cấu trúc, chất lượng và đặc điểm ban đầu của dữ liệu.

Giai đoạn PreEDA được thực hiện trước bước Cleaning & Preprocessing nhằm xác định các vấn đề tiềm ẩn trong dữ liệu như giá trị thiếu, dữ liệu trùng lặp, kiểu dữ liệu không phù hợp và các đặc điểm phân bố ban đầu.

Notebook được xây dựng dựa trên cùng quy trình với Notebook 01 của bộ dữ liệu quốc tế nhằm đảm bảo tính nhất quán trong pipeline nghiên cứu Digital Burnout và tạo cơ sở cho việc so sánh giữa hai bộ dữ liệu.

# 0. Set Up

Thiết lập môi trường phân tích cần thiết cho quá trình PreEDA.

In [22]:
# Import thư viện xử lý dữ liệu

import pandas as pd
import numpy as np


# Import thư viện trực quan hóa

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick


# Import thư viện hỗ trợ

from pathlib import Path
import warnings


# Thiết lập cấu hình hiển thị dữ liệu

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)


# Thiết lập cấu hình biểu đồ

plt.rcParams["figure.figsize"] = (10, 6)
plt.rcParams["axes.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 12


# Tắt các cảnh báo không cần thiết

warnings.filterwarnings("ignore")


# Thiết lập hạt giống ngẫu nhiên

np.random.seed(42)


print("Đã thiết lập môi trường phân tích dữ liệu.")

Đã thiết lập môi trường phân tích dữ liệu.

# 1. Load Dataset

Đọc bộ dữ liệu khảo sát sinh viên Việt Nam từ file CSV và kiểm tra dữ liệu đầu vào trước khi thực hiện các bước phân tích tổng quan.

Giai đoạn này chỉ thực hiện tải dữ liệu và quan sát ban đầu. Không thực hiện bất kỳ thao tác thay đổi hoặc xử lý dữ liệu.

In [26]:
# Khai báo đường dẫn bộ dữ liệu khảo sát

dataset_path = Path("../../data/raw/vietnam_dataset/vn_digital_burnout.csv")


# Đọc bộ dữ liệu khảo sát

survey_dataset = pd.read_csv(dataset_path)


# Hiển thị thông tin cơ bản của bộ dữ liệu

print("Đã tải bộ dữ liệu khảo sát thành công.")

print(f"Số lượng quan sát: {survey_dataset.shape[0]:,}")

print(f"Số lượng biến: {survey_dataset.shape[1]}")


# Hiển thị một số dòng dữ liệu đầu tiên

display(survey_dataset.head())

Đã tải bộ dữ liệu khảo sát thành công.
Số lượng quan sát: 697
Số lượng biến: 28

,Giới tính của bạn?,Năm sinh?,Bạn đang ở giai đoạn nào?,Hình thức học tập / làm việc chính hiện tại:,Mô tả cách bạn dùng thiết bị số hiện tại:,Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?,"Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?\n","Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?",Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?,Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?,Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?,Con người cần hô hấp để sống đúng không?,"Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?",Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,"Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?","Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?","Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?","Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?",Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?,Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,"Mình cảm thấy kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.","Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.",Tôi cảm thấy mệt mỏi về mặt thể chất sau một ngày làm việc/học tập với các thiết bị số.,Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 4),Tôi cảm thấy kiệt sức về mặt cảm xúc sau một ngày làm việc/học tập với các thiết bị số.,Tôi cảm thấy hiệu suất làm việc/học tập của mình bị suy giảm rõ rệt so với trước đây.,Tôi cảm thấy mất dần sự hứng thú hoặc hoài nghi về giá trị của công việc/việc học hiện tại.
0,Nam,2006 - 2008,Vừa học vừa đi làm / thực tập,Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,"Chủ yếu để học (LMS, tài liệu, nghiên cứu)",6-8 giờ,Dưới 1 giờ,1-2 giờ/ngày,1-2 lần/tuần,Trên 150 thông báo/ngày,60-100 lần/ngày,Có,Trên 100 lần,3,3-5 lần,5 lần trở lên,Trên 3 giờ,25-50%,Dưới 5 tiếng,10,8,2,1,4,2,1,2,2
1,Nam,2006 - 2008,Đã đi làm toàn thời gian,"Tự do, không cố định lịch trình","Chủ yếu để giải trí (mạng xã hội, game, xem phim)",6-8 giờ,1-2 giờ,Trên 2 giờ/ngày,Hầu như mỗi tối,Trên 150 thông báo/ngày,60-100 lần/ngày,Không,Trên 100 lần,6,6-10 lần,Không có lần nào,Dưới 1 giờ,Trên 75% - hoàn thành tốt,7-8 tiếng,10,10,5,1,4,5,2,2,2
2,Nam,1997 - 1999,Học sinh THPT,"Tự do, không cố định lịch trình",Chủ yếu giao tiếp nhóm và làm việc cộng tác,Dưới 4 giờ,1-2 giờ,Không bao giờ hoặc rất hiếm,3-5 lần/tuần,80-150 thông báo/ngày,Dưới 30 lần/ngày,Không,20-50 lần,10,0-2 lần (mình kiểm soát được khá tốt),5 lần trở lên,2-3 giờ,25-50%,Trên 8 tiếng,1,5,5,2,2,5,5,1,1
3,Nữ,2009 - 2012,Vừa học vừa đi làm / thực tập,"Kết hợp hybrid (2-3 ngày trực tiếp, còn lại on...",Chủ yếu giao tiếp nhóm và làm việc cộng tác,4-6 giờ,2-4 giờ,Dưới 30 phút/ngày,Không bao giờ,Trên 150 thông báo/ngày,30-60 lần/ngày,Mình không biết,Trên 100 lần,8,3-5 lần,Không có lần nào,1-2 giờ,Trên 75% - hoàn thành tốt,Trên 8 tiếng,5,10,1,5,3,1,4,3,4
4,Nữ,2006 - 2008,Sinh viên đại học / cao đẳng (năm 3-4+),Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...,"Chủ yếu để học (LMS, tài liệu, nghiên cứu)",Dưới 4 giờ,Dưới 1 giờ,Trên 2 giờ/ngày,3-5 lần/tuần,30-80 thông báo/ngày,30-60 lần/ngày,Có,Dưới 20 lần,9,Trên 10 lần (mình gần như bị ngắt liên tục),5 lần trở lên,Trên 3 giờ,25-50%,5-6 tiếng,7,9,4,2,4,4,4,2,1

# 2. Dataset Overview

Khảo sát tổng quan cấu trúc của bộ dữ liệu khảo sát sinh viên Việt Nam nhằm xác định quy mô, kiểu dữ liệu và đặc điểm của từng biến trước khi thực hiện các bước tiền xử lý.

- Kiểm tra thông tin tổng quan của bộ dữ liệu.
- Xác định số lượng quan sát và số lượng biến.
- Phân loại kiểu dữ liệu của từng biến.

In [27]:
# Hiển thị thông tin tổng quan của bộ dữ liệu

print("Thông tin tổng quan của bộ dữ liệu khảo sát:")

survey_dataset.info()

Thông tin tổng quan của bộ dữ liệu khảo sát:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 697 entries, 0 to 696
Data columns (total 28 columns):
 #   Column                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                           --------------  -----
 0   Giới tính của bạn?                                                                                                                               697 non-null    object
 1   Năm sinh?                                                                                                                                        697 non-null    object
 2   Bạn đang ở giai đoạn nào?                                                                                                                        697 non-null    object
 3   Hình thức học tập / làm việc chính hiện tại:                                                                                                     697 non-null    object
 4   Mô tả cách bạn dùng thiết bị số hiện tại:                                                                                                        697 non-null    object
 5   Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ  (gộp cả học/làm lẫn giải trí)?                                      697 non-null    object
 6   Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?
                                               697 non-null    object
 7   Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?                    697 non-null    object
 8   Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?                                                                                      697 non-null    object
 9   Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?                                                                               697 non-null    object
 10  Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?                                                                                            697 non-null    object
 11  Con người cần hô hấp để sống đúng không?                                                                                                         697 non-null    object
 12  Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?                                                          697 non-null    object
 13  Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?                                                                                   697 non-null    int64
 14  Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?                                                   697 non-null    object
 15  Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?                      697 non-null    object
 16  Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?               697 non-null    object
 17  Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?  697 non-null    object
 18  Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?                                                                                697 non-null    object
 19  Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?                                                     697 non-null    int64
 20  Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?                                                                           697 non-null    int64
 21  Mình cảm thấy kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.                        697 non-null    int64
 22  Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.                                   697 non-null    int64
 23  Tôi cảm thấy mệt mỏi về mặt thể chất sau một ngày làm việc/học tập với các thiết bị số.                                                          697 non-null    int64
 24  Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 4)                                                                    697 non-null    int64
 25  Tôi cảm thấy kiệt sức về mặt cảm xúc sau một ngày làm việc/học tập với các thiết bị số.                                                          697 non-null    int64
 26  Tôi cảm thấy hiệu suất làm việc/học tập của mình bị suy giảm rõ rệt so với trước đây.                                                            697 non-null    int64
 27  Tôi cảm thấy mất dần sự hứng thú hoặc hoài nghi về giá trị của công việc/việc học hiện tại.                                                      697 non-null    int64
dtypes: int64(10), object(18)
memory usage: 152.6+ KB

In [28]:
# Thống kê kích thước bộ dữ liệu

dataset_shape = pd.DataFrame(
    {
        "Metric": [
            "Number of Observations",
            "Number of Variables"
        ],
        "Value": [
            survey_dataset.shape[0],
            survey_dataset.shape[1]
        ]
    }
)

print("Kích thước bộ dữ liệu:")

display(dataset_shape)

Kích thước bộ dữ liệu:

                   Metric  Value
0  Number of Observations    697
1     Number of Variables     28

In [31]:
# Liệt kê các biến theo từng kiểu dữ liệu

data_type_table = pd.DataFrame(
    {
        "Variable": survey_dataset.columns,
        "Data Type": survey_dataset.dtypes.astype(str).values
    }
)

print("Danh sách kiểu dữ liệu của từng biến:")

display(data_type_table)

Danh sách kiểu dữ liệu của từng biến:

                                             Variable Data Type
0                                  Giới tính của bạn?    object
1                                           Năm sinh?    object
2                           Bạn đang ở giai đoạn nào?    object
3        Hình thức học tập / làm việc chính hiện tại:    object
4           Mô tả cách bạn dùng thiết bị số hiện tại:    object
5   Trung bình mỗi ngày bạn dùng điện thoại và máy...    object
6   Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hộ...    object
7   Bạn có thường xuyên cuộn feed (TikTok, Reels, ...    object
8   Bạn có thường dùng điện thoại hoặc máy tính sa...    object
9   Bạn nhận khoảng bao nhiêu thông báo trên tất c...    object
10  Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗ...    object
11           Con người cần hô hấp để sống đúng không?    object
12  Trong một ngày học/làm việc, bạn chuyển qua lạ...    object
13  Bạn tự đánh giá khả năng tập trung của mình dạ...     int64
14  Trong 1 giờ học/làm việc, bạn bị kéo ra bởi đi...    object
15  Trong một ngày, bạn có bao nhiêu lần ngồi học ...    object
16  Mỗi ngày bạn dành được bao nhiêu giờ thực sự t...    object
17  Nhìn lại hôm qua, bạn hoàn thành được khoảng b...    object
18  Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (kh...    object
19  Dạo này bạn thấy giấc ngủ của mình như thế nào...     int64
20  Mức độ có động lực để học tập hoặc làm việc củ...     int64
21  Mình cảm thấy kiệt sức chỉ vì phải liên tục nh...     int64
22  Mình thấy căng thẳng, lo lắng khi thấy tin nhắ...     int64
23  Tôi cảm thấy mệt mỏi về mặt thể chất sau một n...     int64
24  Bạn còn đang thực hiện khảo sát này đúng không...     int64
25  Tôi cảm thấy kiệt sức về mặt cảm xúc sau một n...     int64
26  Tôi cảm thấy hiệu suất làm việc/học tập của mì...     int64
27  Tôi cảm thấy mất dần sự hứng thú hoặc hoài ngh...     int64

In [32]:
# Phân nhóm các biến theo kiểu dữ liệu

object_variables = (
    survey_dataset
    .select_dtypes(include="object")
    .columns
    .tolist()
)

numeric_variables = (
    survey_dataset
    .select_dtypes(include=["number"])
    .columns
    .tolist()
)

print(f"Số biến định tính: {len(object_variables)}")

print(f"Số biến định lượng: {len(numeric_variables)}")

Số biến định tính: 18
Số biến định lượng: 10

# 3. Data Quality Assessment

Đánh giá chất lượng ban đầu của bộ dữ liệu khảo sát sinh viên Việt Nam nhằm phát hiện các vấn đề có thể ảnh hưởng đến quá trình phân tích và xây dựng mô hình học máy.

- Kiểm tra giá trị thiếu.
- Kiểm tra bản ghi trùng lặp.
- Thống kê số lượng giá trị khác nhau.
- Thống kê mô tả dữ liệu.

## 3.1 Missing Values

Kiểm tra sự tồn tại của các giá trị thiếu trong bộ dữ liệu.

In [33]:
# Thống kê số lượng và tỷ lệ giá trị thiếu

missing_summary = pd.DataFrame({

    "Variable": survey_dataset.columns,

    "Missing Count": survey_dataset.isna().sum().values,

    "Missing Percentage (%)": (
        survey_dataset.isna().mean() * 100
    ).round(2)

})

missing_summary = missing_summary.sort_values(

    by="Missing Count",
    ascending=False

)

print("Kết quả kiểm tra giá trị thiếu:")

display(missing_summary)

Kết quả kiểm tra giá trị thiếu:

,Variable,Missing Count,Missing Percentage (%)
Giới tính của bạn?,Giới tính của bạn?,0,0.0
Năm sinh?,Năm sinh?,0,0.0
Bạn đang ở giai đoạn nào?,Bạn đang ở giai đoạn nào?,0,0.0
Hình thức học tập / làm việc chính hiện tại:,Hình thức học tập / làm việc chính hiện tại:,0,0.0
Mô tả cách bạn dùng thiết bị số hiện tại:,Mô tả cách bạn dùng thiết bị số hiện tại:,0,0.0
Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?,Trung bình mỗi ngày bạn dùng điện thoại và máy...,0,0.0
"Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?\n",Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hộ...,0,0.0
"Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?","Bạn có thường xuyên cuộn feed (TikTok, Reels, ...",0,0.0
Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?,Bạn có thường dùng điện thoại hoặc máy tính sa...,0,0.0
Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?,Bạn nhận khoảng bao nhiêu thông báo trên tất c...,0,0.0
Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?,Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗ...,0,0.0
Con người cần hô hấp để sống đúng không?,Con người cần hô hấp để sống đúng không?,0,0.0
"Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?","Trong một ngày học/làm việc, bạn chuyển qua lạ...",0,0.0
Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,Bạn tự đánh giá khả năng tập trung của mình dạ...,0,0.0
"Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?","Trong 1 giờ học/làm việc, bạn bị kéo ra bởi đi...",0,0.0
"Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?","Trong một ngày, bạn có bao nhiêu lần ngồi học ...",0,0.0
"Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?",Mỗi ngày bạn dành được bao nhiêu giờ thực sự t...,0,0.0
"Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?","Nhìn lại hôm qua, bạn hoàn thành được khoảng b...",0,0.0
Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?,Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (kh...,0,0.0
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,Dạo này bạn thấy giấc ngủ của mình như thế nào...,0,0.0
Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,Mức độ có động lực để học tập hoặc làm việc củ...,0,0.0
"Mình cảm thấy kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.",Mình cảm thấy kiệt sức chỉ vì phải liên tục nh...,0,0.0
"Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.","Mình thấy căng thẳng, lo lắng khi thấy tin nhắ...",0,0.0
Tôi cảm thấy mệt mỏi về mặt thể chất sau một ngày làm việc/học tập với các thiết bị số.,Tôi cảm thấy mệt mỏi về mặt thể chất sau một n...,0,0.0
Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 4),Bạn còn đang thực hiện khảo sát này đúng không...,0,0.0
Tôi cảm thấy kiệt sức về mặt cảm xúc sau một ngày làm việc/học tập với các thiết bị số.,Tôi cảm thấy kiệt sức về mặt cảm xúc sau một n...,0,0.0
Tôi cảm thấy hiệu suất làm việc/học tập của mình bị suy giảm rõ rệt so với trước đây.,Tôi cảm thấy hiệu suất làm việc/học tập của mì...,0,0.0
Tôi cảm thấy mất dần sự hứng thú hoặc hoài nghi về giá trị của công việc/việc học hiện tại.,Tôi cảm thấy mất dần sự hứng thú hoặc hoài ngh...,0,0.0

## 3.2 Duplicate Records

Kiểm tra sự tồn tại của các bản ghi bị trùng lặp trong bộ dữ liệu khảo sát.

In [34]:
# Thống kê bản ghi trùng lặp

duplicate_count = survey_dataset.duplicated().sum()

duplicate_percentage = (

    duplicate_count
    / len(survey_dataset)

) * 100


duplicate_summary = pd.DataFrame({

    "Metric": [
        "Duplicate Records",
        "Duplicate Percentage (%)"
    ],

    "Value": [
        duplicate_count,
        round(duplicate_percentage, 2)
    ]

})

print("Kết quả kiểm tra bản ghi trùng lặp:")

display(duplicate_summary)

Kết quả kiểm tra bản ghi trùng lặp:

                     Metric  Value
0         Duplicate Records  35.00
1  Duplicate Percentage (%)   5.02

## 3.3 Unique Values

Kiểm tra số lượng giá trị duy nhất của từng biến nhằm hiểu rõ đặc điểm của các biến trong dataset.

In [35]:
# Thống kê số lượng giá trị khác nhau

unique_summary = pd.DataFrame({

    "Variable": survey_dataset.columns,
    "Unique Values": survey_dataset.nunique().values

})

unique_summary = unique_summary.sort_values(

    by="Unique Values",
    ascending=False

)

print("Thống kê số lượng giá trị khác nhau:")

display(unique_summary)

Thống kê số lượng giá trị khác nhau:

                                             Variable  Unique Values
19  Dạo này bạn thấy giấc ngủ của mình như thế nào...             10
20  Mức độ có động lực để học tập hoặc làm việc củ...             10
13  Bạn tự đánh giá khả năng tập trung của mình dạ...             10
2                           Bạn đang ở giai đoạn nào?              7
24  Bạn còn đang thực hiện khảo sát này đúng không...              5
21  Mình cảm thấy kiệt sức chỉ vì phải liên tục nh...              5
22  Mình thấy căng thẳng, lo lắng khi thấy tin nhắ...              5
23  Tôi cảm thấy mệt mỏi về mặt thể chất sau một n...              5
18  Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (kh...              5
1                                           Năm sinh?              5
7   Bạn có thường xuyên cuộn feed (TikTok, Reels, ...              5
5   Trung bình mỗi ngày bạn dùng điện thoại và máy...              5
26  Tôi cảm thấy hiệu suất làm việc/học tập của mì...              5
25  Tôi cảm thấy kiệt sức về mặt cảm xúc sau một n...              5
27  Tôi cảm thấy mất dần sự hứng thú hoặc hoài ngh...              5
10  Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗ...              4
6   Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hộ...              4
4           Mô tả cách bạn dùng thiết bị số hiện tại:              4
3        Hình thức học tập / làm việc chính hiện tại:              4
8   Bạn có thường dùng điện thoại hoặc máy tính sa...              4
12  Trong một ngày học/làm việc, bạn chuyển qua lạ...              4
17  Nhìn lại hôm qua, bạn hoàn thành được khoảng b...              4
9   Bạn nhận khoảng bao nhiêu thông báo trên tất c...              4
16  Mỗi ngày bạn dành được bao nhiêu giờ thực sự t...              4
14  Trong 1 giờ học/làm việc, bạn bị kéo ra bởi đi...              4
15  Trong một ngày, bạn có bao nhiêu lần ngồi học ...              4
11           Con người cần hô hấp để sống đúng không?              3
0                                  Giới tính của bạn?              2

## 3.4 Descriptive Statistics

Phân tích thống kê mô tả nhằm quan sát đặc điểm phân bố ban đầu của các biến trong dataset.

In [36]:
# Thống kê mô tả các biến định lượng

numeric_summary = survey_dataset.describe().T

print("Thống kê mô tả các biến định lượng:")

display(numeric_summary)

Thống kê mô tả các biến định lượng:

,count,mean,std,min,25%,50%,75%,max
Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?,697.0,5.454806,2.196793,1.0,4.0,6.0,7.0,10.0
Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?,697.0,5.139168,1.994065,1.0,4.0,5.0,6.0,10.0
Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?,697.0,5.332855,2.171781,1.0,3.0,5.0,7.0,10.0
"Mình cảm thấy kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.",697.0,3.572453,1.071168,1.0,3.0,4.0,4.0,5.0
"Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.",697.0,3.923960,1.127612,1.0,3.0,4.0,5.0,5.0
Tôi cảm thấy mệt mỏi về mặt thể chất sau một ngày làm việc/học tập với các thiết bị số.,697.0,3.599713,1.136717,1.0,3.0,4.0,4.0,5.0
Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 4),697.0,3.944046,0.402610,1.0,4.0,4.0,4.0,5.0
Tôi cảm thấy kiệt sức về mặt cảm xúc sau một ngày làm việc/học tập với các thiết bị số.,697.0,3.427547,1.080517,1.0,3.0,3.0,4.0,5.0
Tôi cảm thấy hiệu suất làm việc/học tập của mình bị suy giảm rõ rệt so với trước đây.,697.0,3.509326,0.991479,1.0,3.0,4.0,4.0,5.0
Tôi cảm thấy mất dần sự hứng thú hoặc hoài nghi về giá trị của công việc/việc học hiện tại.,697.0,3.094692,1.036510,1.0,2.0,3.0,4.0,5.0

In [37]:
# Thống kê các biến định tính

categorical_summary = pd.DataFrame({

    "Variable": object_variables,

    "Unique Values": [
        survey_dataset[column].nunique()
        for column in object_variables
    ],

    "Most Frequent Value": [
        survey_dataset[column].mode().iloc[0]
        for column in object_variables
    ]

})

print("Thống kê các biến định tính:")

display(categorical_summary)

Thống kê các biến định tính:

,Variable,Unique Values,Most Frequent Value
0,Giới tính của bạn?,2,Nữ
1,Năm sinh?,5,2003 - 2005
2,Bạn đang ở giai đoạn nào?,7,Sinh viên đại học / cao đẳng (năm 3-4+)
3,Hình thức học tập / làm việc chính hiện tại:,4,Hoàn toàn trực tiếp (đến trường / văn phòng ≥ ...
4,Mô tả cách bạn dùng thiết bị số hiện tại:,4,Cân bằng cả học lẫn giải trí
5,Trung bình mỗi ngày bạn dùng điện thoại và máy...,5,8-10 giờ
6,Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hộ...,4,2-4 giờ
7,"Bạn có thường xuyên cuộn feed (TikTok, Reels, ...",5,1-2 giờ/ngày
8,Bạn có thường dùng điện thoại hoặc máy tính sa...,4,Hầu như mỗi tối
9,Bạn nhận khoảng bao nhiêu thông báo trên tất c...,4,30-80 thông báo/ngày
10,Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗ...,4,30-60 lần/ngày
11,Con người cần hô hấp để sống đúng không?,3,Có
12,"Trong một ngày học/làm việc, bạn chuyển qua lạ...",4,20-50 lần
13,"Trong 1 giờ học/làm việc, bạn bị kéo ra bởi đi...",4,6-10 lần
14,"Trong một ngày, bạn có bao nhiêu lần ngồi học ...",4,3-4 lần
15,Mỗi ngày bạn dành được bao nhiêu giờ thực sự t...,4,2-3 giờ
16,"Nhìn lại hôm qua, bạn hoàn thành được khoảng b...",4,25-50%
17,Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (kh...,5,5-6 tiếng

# 4. Survey Structure Overview

Khảo sát cấu trúc của bộ câu hỏi trong khảo sát sinh viên Việt Nam nhằm xác định vai trò của từng nhóm biến trong khung nghiên cứu Digital Burnout.

Các câu hỏi trong khảo sát được xây dựng dựa trên khung nghiên cứu Digital Burnout và được chia thành các nhóm chức năng khác nhau, bao gồm:

- Demographic Variables
- Digital Exposure Indicators
- Cognitive Performance Indicators
- Sleep & Recovery Indicators
- Digital Burnout Scale Items
- Attention Check Items

Việc phân nhóm này giúp xác định rõ vai trò của từng biến trước khi thực hiện tiền xử lý dữ liệu và xây dựng mô hình học máy.

## 4.1 Demographic Variables

Khảo sát các biến mô tả đặc điểm của đối tượng tham gia khảo sát.

Nhóm biến này phản ánh đặc điểm cá nhân và bối cảnh học tập của sinh viên. Các biến này có thể được sử dụng như các biến đầu vào trong quá trình xây dựng mô hình học máy.

In [38]:
# Khai báo nhóm biến nhân khẩu học

demographic_variables = [

    "Giới tính của bạn?",
    "Năm sinh?",
    "Bạn đang ở giai đoạn nào?",
    "Hình thức học tập / làm việc chính hiện tại:",
    "Mô tả cách bạn dùng thiết bị số hiện tại:"

]


# Hiển thị danh sách biến

demographic_summary = pd.DataFrame({
    "Variable": demographic_variables
})

print("Nhóm biến nhân khẩu học:")

display(demographic_summary)

Nhóm biến nhân khẩu học:

                                       Variable
0                            Giới tính của bạn?
1                                     Năm sinh?
2                     Bạn đang ở giai đoạn nào?
3  Hình thức học tập / làm việc chính hiện tại:
4     Mô tả cách bạn dùng thiết bị số hiện tại:

## 4.2 Digital Exposure Indicators

Khảo sát các chỉ báo phản ánh mức độ tiếp xúc với thiết bị số của sinh viên.

Nhóm biến này mô tả cường độ và thói quen sử dụng thiết bị số trong cuộc sống hằng ngày.

In [39]:
# Khai báo nhóm chỉ báo Digital Exposure

digital_exposure_variables = [

    "Trung bình mỗi ngày bạn dùng điện thoại và máy tính tổng cộng bao nhiêu giờ (gộp cả học/làm lẫn giải trí)?",
    "Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hội (TikTok, Instagram, Facebook, YouTube Shorts...)?\n",
    "Bạn có thường xuyên cuộn feed (TikTok, Reels, Shorts...) liên tục không có mục đích rõ ràng? Nếu có, mỗi ngày khoảng bao lâu?",
    "Bạn có thường dùng điện thoại hoặc máy tính sau 22 giờ đêm?",
    "Bạn nhận khoảng bao nhiêu thông báo trên tất cả ứng dụng mỗi ngày?",
    "Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗi ngày?",
    "Trong một ngày học/làm việc, bạn chuyển qua lại giữa ứng dụng/tab khoảng bao nhiêu lần?"

]

digital_exposure_summary = pd.DataFrame({
    "Variable": digital_exposure_variables
})

print("Nhóm chỉ báo Digital Exposure:")

display(digital_exposure_summary)

Nhóm chỉ báo Digital Exposure:

                                            Variable
0  Trung bình mỗi ngày bạn dùng điện thoại và máy...
1  Bạn dành bao nhiêu giờ mỗi ngày cho mạng xã hộ...
2  Bạn có thường xuyên cuộn feed (TikTok, Reels, ...
3  Bạn có thường dùng điện thoại hoặc máy tính sa...
4  Bạn nhận khoảng bao nhiêu thông báo trên tất c...
5  Bạn mở khóa điện thoại khoảng bao nhiêu lần mỗ...
6  Trong một ngày học/làm việc, bạn chuyển qua lạ...

## 4.3 Cognitive Performance Indicators

Khảo sát các chỉ báo phản ánh khả năng tập trung và hiệu suất học tập/làm việc của sinh viên.

Nhóm biến này mô tả khả năng duy trì sự tập trung, hạn chế phân tâm và mức độ hoàn thành công việc trong quá trình học tập hoặc làm việc.

In [40]:
# Khai báo nhóm chỉ báo Cognitive Performance

cognitive_performance_variables = [

    "Bạn tự đánh giá khả năng tập trung của mình dạo này ở mức nào?",
    "Trong 1 giờ học/làm việc, bạn bị kéo ra bởi điện thoại, thông báo hoặc tab khác bao nhiêu lần?",
    "Trong một ngày, bạn có bao nhiêu lần ngồi học hoặc làm việc liên tục ít nhất 25 phút mà không mở điện thoại hay chuyển tab?",
    "Mỗi ngày bạn dành được bao nhiêu giờ thực sự tập trung sâu vào việc học/làm - không mạng xã hội, không thông báo, không multitask?",
    "Nhìn lại hôm qua, bạn hoàn thành được khoảng bao nhiêu phần trăm những việc mình đã đặt ra (bài tập, deadline, công việc, nhiệm vụ cá nhân...)?"

]

cognitive_performance_summary = pd.DataFrame({
    "Variable": cognitive_performance_variables
})

print("Nhóm chỉ báo Cognitive Performance:")

display(cognitive_performance_summary)

Nhóm chỉ báo Cognitive Performance:

                                            Variable
0  Bạn tự đánh giá khả năng tập trung của mình dạ...
1  Trong 1 giờ học/làm việc, bạn bị kéo ra bởi đi...
2  Trong một ngày, bạn có bao nhiêu lần ngồi học ...
3  Mỗi ngày bạn dành được bao nhiêu giờ thực sự t...
4  Nhìn lại hôm qua, bạn hoàn thành được khoảng b...

## 4.4 Sleep & Recovery Indicators

Khảo sát các chỉ báo phản ánh khả năng nghỉ ngơi và phục hồi của sinh viên.

Nhóm biến này đánh giá thời lượng ngủ, chất lượng giấc ngủ và mức độ động lực học tập hoặc làm việc.

In [41]:
# Khai báo nhóm chỉ báo Sleep & Recovery

sleep_recovery_variables = [

    "Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (không tính ngủ trưa)?",
    "Dạo này bạn thấy giấc ngủ của mình như thế nào? Khi thức dậy có thấy khỏe và tỉnh táo không?",
    "Mức độ có động lực để học tập hoặc làm việc của bạn dạo này ở mức nào?"

]

sleep_recovery_summary = pd.DataFrame({
    "Variable": sleep_recovery_variables
})

print("Nhóm chỉ báo Sleep & Recovery:")

display(sleep_recovery_summary)

Nhóm chỉ báo Sleep & Recovery:

                                            Variable
0  Trung bình bạn ngủ bao nhiêu tiếng mỗi đêm (kh...
1  Dạo này bạn thấy giấc ngủ của mình như thế nào...
2  Mức độ có động lực để học tập hoặc làm việc củ...

## 4.5 Digital Burnout Scale Items

Khảo sát các mục của thang đo Digital Burnout được sử dụng để xây dựng biến mục tiêu trong nghiên cứu.

Các câu hỏi trong nhóm này phản ánh các biểu hiện tâm lý và hành vi đặc trưng của Digital Burnout, bao gồm kiệt sức, căng thẳng, mệt mỏi, suy giảm hiệu suất và mất hứng thú.

In [42]:
# Khai báo các mục của thang đo Digital Burnout

digital_burnout_scale_items = [

    "Mình cảm thấy kiệt sức chỉ vì phải liên tục nhìn màn hình và xử lý thông tin cả ngày, kể cả khi làm những thứ mình thích.",
    "Mình thấy căng thẳng, lo lắng khi thấy tin nhắn chưa đọc, thông báo chưa xử lý, hoặc deadline đang chồng chất.",
    "Tôi cảm thấy mệt mỏi về mặt thể chất sau một ngày làm việc/học tập với các thiết bị số.",
    "Tôi cảm thấy kiệt sức về mặt cảm xúc sau một ngày làm việc/học tập với các thiết bị số.",
    "Tôi cảm thấy hiệu suất làm việc/học tập của mình bị suy giảm rõ rệt so với trước đây.",
    "Tôi cảm thấy mất dần sự hứng thú hoặc hoài nghi về giá trị của công việc/việc học hiện tại."

]

digital_burnout_scale_summary = pd.DataFrame({
    "Variable": digital_burnout_scale_items
})

print("Các mục của thang đo Digital Burnout:")

display(digital_burnout_scale_summary)

Các mục của thang đo Digital Burnout:

                                            Variable
0  Mình cảm thấy kiệt sức chỉ vì phải liên tục nh...
1  Mình thấy căng thẳng, lo lắng khi thấy tin nhắ...
2  Tôi cảm thấy mệt mỏi về mặt thể chất sau một n...
3  Tôi cảm thấy kiệt sức về mặt cảm xúc sau một n...
4  Tôi cảm thấy hiệu suất làm việc/học tập của mì...
5  Tôi cảm thấy mất dần sự hứng thú hoặc hoài ngh...

## 4.6 Attention Check Items

Khảo sát các câu hỏi được sử dụng để đánh giá mức độ nghiêm túc của người tham gia khảo sát.

Các câu hỏi này được thiết kế nhằm phát hiện các phản hồi thiếu tập trung hoặc trả lời ngẫu nhiên.

In [43]:
# Khai báo các câu hỏi Attention Check

attention_check_items = [
    
    "Con người cần hô hấp để sống đúng không?",
    "Bạn còn đang thực hiện khảo sát này đúng không? (Nếu đúng vui lòng chọn số 4)"
    
]

attention_check_summary = pd.DataFrame({
    "Variable": attention_check_items
})

print("Các câu hỏi Attention Check:")

display(attention_check_summary)

Các câu hỏi Attention Check:

                                            Variable
0           Con người cần hô hấp để sống đúng không?
1  Bạn còn đang thực hiện khảo sát này đúng không...

## 4.7 Summary of Survey Variables

Tổng hợp cấu trúc của bộ câu hỏi khảo sát theo từng nhóm chức năng trong khung nghiên cứu Digital Burnout.

Thống kê số lượng biến và vai trò của từng nhóm nhằm cung cấp cái nhìn tổng quan về cấu trúc bộ dữ liệu khảo sát.

In [44]:
# Tổng hợp số lượng biến theo từng nhóm

survey_structure_summary = pd.DataFrame({

    "Variable Group": [
        "Demographic Variables",
        "Digital Exposure Indicators",
        "Cognitive Performance Indicators",
        "Sleep & Recovery Indicators",
        "Digital Burnout Scale Items",
        "Attention Check Items"
    ],

    "Number of Variables": [
        len(demographic_variables),
        len(digital_exposure_variables),
        len(cognitive_performance_variables),
        len(sleep_recovery_variables),
        len(digital_burnout_scale_items),
        len(attention_check_items)
    ],

    "Purpose": [
        "Participant Profile",
        "Digital Behavior",
        "Learning Performance",
        "Recovery Status",
        "Target Construction",
        "Response Validation"
    ]

})

print("Tổng quan cấu trúc khảo sát:")

display(survey_structure_summary)

Tổng quan cấu trúc khảo sát:

                     Variable Group  Number of Variables               Purpose
0             Demographic Variables                    5   Participant Profile
1       Digital Exposure Indicators                    7      Digital Behavior
2  Cognitive Performance Indicators                    5  Learning Performance
3       Sleep & Recovery Indicators                    3       Recovery Status
4       Digital Burnout Scale Items                    6   Target Construction
5             Attention Check Items                    2   Response Validation