# Notebook 02. Comparative Analysis

Notebook này thực hiện phân tích so sánh giữa International Dataset và Vietnam Dataset nhằm đánh giá sự khác biệt và mức độ tương đồng của Digital Burnout Framework sau khi đã được tinh chỉnh ở Notebook 01 (DBI Refinement).

Thay vì tiếp tục lựa chọn hoặc xây dựng indicator, notebook này sử dụng bộ Core DBI Framework đã được xác định để trả lời ba câu hỏi chính:

1. Bộ chỉ số DBI có biểu hiện tương đồng giữa hai nhóm dữ liệu hay không?
2. Các đặc trưng ảnh hưởng đến Digital Burnout có sự khác biệt như thế nào giữa hai dataset?
3. Các mô hình Machine Learning có khả năng dự đoán Digital Burnout khác nhau như thế nào giữa hai bối cảnh dữ liệu?

# 0. Set Up

Thiết lập môi trường phân tích cho quá trình Comparative Analysis giữa International Dataset và Vietnam Dataset.

Phần này chuẩn bị các thư viện cần thiết, xác định đường dẫn dữ liệu và kiểm tra các file đầu vào được sử dụng trong notebook.

In [1]:
# Import các thư viện cần thiết cho quá trình phân tích

import pandas as pd
import numpy as np

from pathlib import Path

from IPython.display import display

In [2]:
# Thiết lập đường dẫn thư mục dự án

project_path = Path("../../")

data_path = project_path / "data"

results_path = project_path / "results"

models_path = project_path / "models"

In [3]:
# Xác định đường dẫn dữ liệu DBI Framework

final_data_path = (
    data_path / "final"
)

In [4]:
# Xác định đường dẫn kết quả phân tích đặc trưng

international_results_path = (
    results_path / "international_dataset"
)

vietnam_results_path = (
    results_path / "vietnam_dataset"
)

In [5]:
# Xác định đường dẫn kết quả mô hình đã huấn luyện

international_models_path = (
    models_path / "international_dataset"
)

vietnam_models_path = (
    models_path / "vietnam_dataset"
)

In [6]:
# Xác định đường dẫn lưu kết quả Comparative Analysis

cross_dataset_results_path = (
    results_path / "cross_dataset"
)

In [7]:
# Kiểm tra sự tồn tại của các thư mục dữ liệu đầu vào

required_paths = {
    "Final DBI Framework": final_data_path,
    "International Results": international_results_path,
    "Vietnam Results": vietnam_results_path,
    "International Models": international_models_path,
    "Vietnam Models": vietnam_models_path
}


for path_name, path_value in required_paths.items():

    if path_value.exists():
        print(f"{path_name}: Đã tìm thấy.")

    else:
        print(f"{path_name}: Chưa tìm thấy.")

Final DBI Framework: Đã tìm thấy.
International Results: Đã tìm thấy.
Vietnam Results: Đã tìm thấy.
International Models: Đã tìm thấy.
Vietnam Models: Đã tìm thấy.

In [8]:
# Tạo thư mục lưu kết quả Comparative Analysis nếu chưa tồn tại

cross_dataset_results_path.mkdir(
    parents=True,
    exist_ok=True
)


print("Đã chuẩn bị thư mục lưu kết quả phân tích.")

Đã chuẩn bị thư mục lưu kết quả phân tích.

# 1. DBI Comparison

Phân tích và so sánh Digital Burnout Indicator (DBI) giữa International Dataset và Vietnam Dataset dựa trên bộ Core DBI Framework đã được hoàn thiện trong Notebook 01 (DBI Refinement).

Phần này nhằm đánh giá mức độ tương đồng và khác biệt của biểu hiện Digital Burnout giữa hai nhóm dữ liệu, từ đó xác định khả năng áp dụng của DBI Framework trong các bối cảnh nghiên cứu khác nhau.

DBI Comparison tập trung vào việc so sánh các thành phần đã được xác định trong Core DBI Framework, bao gồm:

- Các nhóm chỉ số DBI (DBI Dimensions).
- Các indicator thuộc Core DBI Framework.
- Mức độ xuất hiện của indicator giữa hai dataset.

Quá trình phân tích chỉ sử dụng các indicator đã được lựa chọn từ Notebook 01, không thực hiện lại quá trình validation hoặc refinement.

## 1.1 Load DBI Framework

Tải bộ DBI Framework đã được hoàn thiện từ Notebook 01 để làm nguồn dữ liệu chính cho quá trình so sánh giữa International Dataset và Vietnam Dataset.

Các bảng được sử dụng bao gồm:

- Final DBI Framework: chứa toàn bộ indicator, dimension và thông tin phân loại của framework.
- Core DBI Indicator: chứa nhóm indicator cốt lõi được lựa chọn để xây dựng DBI Framework chung.

Các dữ liệu này được sử dụng để:

- Xác định các nhóm DBI Dimension.
- Phân tích sự phân bố indicator.
- So sánh mức độ tương đồng giữa hai dataset.

In [9]:
# Đọc Final DBI Framework

final_dbi_framework = pd.read_csv(
    final_data_path / "final_dbi_framework.csv"
)


# Đọc Core DBI Indicator Framework

core_dbi_indicators = pd.read_csv(
    final_data_path / "core_dbi_indicators.csv"
)

In [10]:
# Kiểm tra cấu trúc dữ liệu DBI Framework

print(
    f"Số lượng indicator trong Final DBI Framework: {final_dbi_framework.shape[0]}"
)

print(
    f"Số lượng Core DBI Indicator: {core_dbi_indicators.shape[0]}"
)

Số lượng indicator trong Final DBI Framework: 31
Số lượng Core DBI Indicator: 16

In [11]:
# Hiển thị một số dòng dữ liệu của DBI Framework

display(
    final_dbi_framework.head()
)

display(
    core_dbi_indicators.head()
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator
1,stress_level,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
2,mental_fatigue,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
3,digital_exhaustion,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator
4,digital_stress,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator
1,daily_screen_time,Digital Exposure,Common,True,True,True,True,Core Indicator
2,social_media_hours,Digital Exposure,Common,True,True,True,True,Core Indicator
3,doomscrolling_duration,Digital Exposure,Common,True,True,True,True,Core Indicator
4,late_night_device_usage,Digital Exposure,Common,True,True,True,True,Core Indicator

## 1.2 DBI Dimension Comparison

Phân tích cấu trúc tổng thể của Final DBI Framework gồm 31 indicator thông qua sự phân bố của các indicator theo từng DBI Dimension.

Phần này nhằm đánh giá mức độ bao phủ của framework trước khi thực hiện các phân tích chuyên sâu về indicator chung và indicator đặc thù giữa hai dataset.

Final DBI Framework được phân tích theo các nhóm dimension:

- Psychological Symptoms.
- Digital Exposure.
- Cognitive Performance.
- Sleep & Recovery.
- Context Variables.

Các bước thực hiện:

- Thống kê số lượng indicator trong từng dimension.
- Tính tỷ lệ đóng góp của từng dimension trong toàn bộ DBI Framework.
- Đánh giá cấu trúc đa chiều của DBI.

In [12]:
# Thống kê số lượng indicator theo từng DBI Dimension

dbi_dimension_summary = (
    final_dbi_framework
    .groupby("dbi_dimension")
    .agg(
        indicator_count=("indicator", "count")
    )
    .reset_index()
)


display(
    dbi_dimension_summary
)

            dbi_dimension  indicator_count
0   Cognitive Performance                8
1       Context Variables                4
2        Digital Exposure                8
3  Psychological Symptoms                6
4        Sleep & Recovery                5

In [13]:
# Tính tỷ lệ phân bố indicator theo từng dimension

dbi_dimension_summary["percentage"] = (
    dbi_dimension_summary["indicator_count"]
    /
    final_dbi_framework.shape[0]
    *
    100
)


display(
    dbi_dimension_summary
)

            dbi_dimension  indicator_count  percentage
0   Cognitive Performance                8   25.806452
1       Context Variables                4   12.903226
2        Digital Exposure                8   25.806452
3  Psychological Symptoms                6   19.354839
4        Sleep & Recovery                5   16.129032

In [14]:
# Sắp xếp dimension theo số lượng indicator giảm dần

dbi_dimension_summary = (
    dbi_dimension_summary
    .sort_values(
        by="indicator_count",
        ascending=False
    )
    .reset_index(drop=True)
)


display(
    dbi_dimension_summary
)

            dbi_dimension  indicator_count  percentage
0   Cognitive Performance                8   25.806452
1        Digital Exposure                8   25.806452
2  Psychological Symptoms                6   19.354839
3        Sleep & Recovery                5   16.129032
4       Context Variables                4   12.903226

## 1.3 Indicator Coverage Comparison

Phân tích mức độ tương đồng và khác biệt của các indicator trong Final DBI Framework giữa International Dataset và Vietnam Dataset.

Phần này nhằm xác định các indicator có khả năng tổng quát hóa giữa hai bối cảnh dữ liệu và các indicator chỉ phản ánh đặc điểm riêng của từng dataset.

Final DBI Framework gồm 31 indicator được phân loại dựa trên thuộc tính coverage:

- Common:
  - Indicator xuất hiện trong cả International Dataset và Vietnam Dataset.
  - Có khả năng đại diện chung cho Digital Burnout Framework.

- International Only:
  - Indicator chỉ xuất hiện trong International Dataset.
  - Phản ánh đặc điểm riêng của bộ dữ liệu quốc tế.

- Vietnam Only:
  - Indicator chỉ xuất hiện trong Vietnam Dataset.
  - Phản ánh đặc điểm riêng của nhóm sinh viên Việt Nam.

Các phân tích thực hiện:

- Thống kê số lượng indicator theo coverage.
- Phân tích coverage theo từng DBI Dimension.
- Xác định mức độ giao nhau giữa hai dataset.

In [15]:
# Thống kê số lượng indicator theo coverage

indicator_coverage_summary = (
    final_dbi_framework
    .groupby("coverage")
    .agg(
        indicator_count=("indicator", "count")
    )
    .reset_index()
)


display(
    indicator_coverage_summary
)

             coverage  indicator_count
0              Common               16
1  International Only               10
2        Vietnam Only                5

In [16]:
# Thống kê coverage của indicator theo từng DBI Dimension

dimension_coverage_summary = (
    final_dbi_framework
    .groupby(
        [
            "dbi_dimension",
            "coverage"
        ]
    )
    .agg(
        indicator_count=("indicator", "count")
    )
    .reset_index()
)


display(
    dimension_coverage_summary
)

             dbi_dimension            coverage  indicator_count
0    Cognitive Performance              Common                6
1    Cognitive Performance  International Only                1
2    Cognitive Performance        Vietnam Only                1
3        Context Variables  International Only                4
4         Digital Exposure              Common                7
5         Digital Exposure  International Only                1
6   Psychological Symptoms              Common                1
7   Psychological Symptoms  International Only                2
8   Psychological Symptoms        Vietnam Only                3
9         Sleep & Recovery              Common                2
10        Sleep & Recovery  International Only                2
11        Sleep & Recovery        Vietnam Only                1

In [17]:
# Lấy danh sách indicator xuất hiện ở cả hai dataset

common_indicators = (
    final_dbi_framework[
        final_dbi_framework["coverage"] == "Common"
    ]
    .reset_index(drop=True)
)


display(
    common_indicators
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator
1,daily_screen_time,Digital Exposure,Common,True,True,True,True,Core Indicator
2,social_media_hours,Digital Exposure,Common,True,True,True,True,Core Indicator
3,doomscrolling_duration,Digital Exposure,Common,True,True,True,True,Core Indicator
4,late_night_device_usage,Digital Exposure,Common,True,True,True,True,Core Indicator
5,notification_count,Digital Exposure,Common,True,True,True,True,Core Indicator
6,smartphone_unlocks,Digital Exposure,Common,True,True,True,True,Core Indicator
7,app_switch_frequency,Digital Exposure,Common,True,True,True,True,Core Indicator
8,concentration_score,Cognitive Performance,Common,True,True,True,True,Core Indicator
9,distraction_frequency,Cognitive Performance,Common,True,True,True,True,Core Indicator
10,focus_sessions,Cognitive Performance,Common,True,True,True,True,Core Indicator
11,deep_work_hours,Cognitive Performance,Common,True,True,True,True,Core Indicator
12,task_completion_rate,Cognitive Performance,Common,True,True,True,True,Core Indicator
13,motivation_level,Cognitive Performance,Common,True,True,True,True,Core Indicator
14,sleep_hours,Sleep & Recovery,Common,True,True,True,True,Core Indicator
15,sleep_quality,Sleep & Recovery,Common,True,True,True,True,Core Indicator

In [18]:
# Lấy danh sách indicator đặc thù theo từng dataset

dataset_specific_indicators = (
    final_dbi_framework[
        final_dbi_framework["coverage"] != "Common"
    ]
    .reset_index(drop=True)
)


display(
    dataset_specific_indicators
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,stress_level,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
1,mental_fatigue,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
2,digital_exhaustion,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator
3,digital_stress,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator
4,loss_of_interest,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator
5,meeting_hours,Digital Exposure,International Only,True,False,True,False,Dataset-specific Indicator
6,performance_decline,Cognitive Performance,Vietnam Only,False,True,False,False,Dataset-specific Indicator
7,work_satisfaction,Cognitive Performance,International Only,True,False,True,False,Dataset-specific Indicator
8,physical_activity,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator
9,physical_fatigue,Sleep & Recovery,Vietnam Only,False,True,False,False,Dataset-specific Indicator
10,caffeine_intake,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator
11,age,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator
12,workspace_quality,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator
13,internet_stability,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator
14,remote_work_days,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator

Kết quả phân tích coverage của Final DBI Framework cho thấy 31 indicator được chia thành hai nhóm chính gồm Common Indicator và Dataset-specific Indicator.

Nhóm Common Indicator gồm 16 indicator, xuất hiện đồng thời trong cả International Dataset và Vietnam Dataset. Các indicator này tập trung chủ yếu vào bốn nhóm dimension chính:

- Digital Exposure với 7 indicator, bao gồm các hành vi sử dụng thiết bị số như thời gian sử dụng màn hình, sử dụng mạng xã hội, doomscrolling, thông báo, số lần mở khóa thiết bị và tần suất chuyển đổi ứng dụng.
- Cognitive Performance với 6 indicator, phản ánh khả năng tập trung, duy trì hiệu suất học tập/làm việc và khả năng quản lý sự chú ý.
- Sleep & Recovery với 2 indicator, đại diện cho khả năng phục hồi thông qua thời lượng và chất lượng giấc ngủ.
- Psychological Symptoms với 1 indicator là emotional_exhaustion, phản ánh biểu hiện kiệt sức cảm xúc chung giữa hai nhóm dữ liệu.

Bên cạnh đó, 15 indicator được xác định là Dataset-specific Indicator, thể hiện sự khác biệt về đặc điểm dữ liệu giữa hai bối cảnh nghiên cứu.

Đối với International Dataset, các indicator đặc thù chủ yếu liên quan đến:
- Stress và trạng thái tâm lý như stress_level, mental_fatigue.
- Đặc điểm môi trường làm việc như meeting_hours, work_satisfaction, workspace_quality, internet_stability và remote_work_days.
- Các yếu tố lối sống như physical_activity, caffeine_intake.
- Đặc điểm nhân khẩu học như age.

Trong khi đó, Vietnam Dataset có các indicator đặc thù phản ánh rõ hơn đặc điểm của nhóm sinh viên Việt Nam:
- Các biểu hiện tâm lý liên quan đến môi trường số như digital_exhaustion, digital_stress và loss_of_interest.
- Suy giảm hiệu suất và trạng thái thể chất như performance_decline và physical_fatigue.

Kết quả này cho thấy Digital Burnout Framework có khả năng duy trì một tập hợp indicator chung có tính tổng quát giữa hai dataset, đồng thời vẫn giữ lại các indicator đặc thù nhằm phản ánh sự khác biệt về bối cảnh nghiên cứu.

Nhóm Common Indicator sẽ là cơ sở để xây dựng Core DBI Framework, trong khi Dataset-specific Indicator được giữ lại như các thành phần bổ sung nhằm thích nghi với từng nhóm đối tượng và môi trường khảo sát.

## 1.4 Core DBI Stability Assessment

Đánh giá mức độ ổn định của Core DBI Framework thông qua việc kiểm tra sự nhất quán của các indicator giữa International Dataset và Vietnam Dataset.

Phần này nhằm xác định liệu các indicator chung giữa hai dataset có duy trì được vai trò quan trọng trong việc giải thích Digital Burnout hay không.

Các Common Indicator được đánh giá dựa trên ba nhóm bằng chứng:

- Coverage: Indicator xuất hiện trong cả hai dataset.
- Feature Validation: Indicator được xác nhận có ý nghĩa trong quá trình kiểm định feature.
- SHAP Feature Importance: Indicator đóng vai trò quan trọng trong việc giải thích dự đoán của mô hình.

Một indicator được xem là Core Indicator khi có tính ổn định cao giữa hai dataset và có đủ bằng chứng hỗ trợ từ quá trình validation.

In [19]:
# Lọc các indicator thuộc Core DBI Framework

core_dbi_indicators = (
    final_dbi_framework[
        final_dbi_framework["indicator_priority"] == "Core Indicator"
    ]
    .reset_index(drop=True)
)


display(
    core_dbi_indicators
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator
1,daily_screen_time,Digital Exposure,Common,True,True,True,True,Core Indicator
2,social_media_hours,Digital Exposure,Common,True,True,True,True,Core Indicator
3,doomscrolling_duration,Digital Exposure,Common,True,True,True,True,Core Indicator
4,late_night_device_usage,Digital Exposure,Common,True,True,True,True,Core Indicator
5,notification_count,Digital Exposure,Common,True,True,True,True,Core Indicator
6,smartphone_unlocks,Digital Exposure,Common,True,True,True,True,Core Indicator
7,app_switch_frequency,Digital Exposure,Common,True,True,True,True,Core Indicator
8,concentration_score,Cognitive Performance,Common,True,True,True,True,Core Indicator
9,distraction_frequency,Cognitive Performance,Common,True,True,True,True,Core Indicator
10,focus_sessions,Cognitive Performance,Common,True,True,True,True,Core Indicator
11,deep_work_hours,Cognitive Performance,Common,True,True,True,True,Core Indicator
12,task_completion_rate,Cognitive Performance,Common,True,True,True,True,Core Indicator
13,motivation_level,Cognitive Performance,Common,True,True,True,True,Core Indicator
14,sleep_hours,Sleep & Recovery,Common,True,True,True,True,Core Indicator
15,sleep_quality,Sleep & Recovery,Common,True,True,True,True,Core Indicator

In [20]:
# Tổng hợp mức độ hỗ trợ của Core Indicator từ validation và SHAP

core_dbi_stability_summary = (
    core_dbi_indicators[
        [
            "indicator",
            "international_validation",
            "vietnam_validation",
            "international_shap",
            "vietnam_shap"
        ]
    ]
    .copy()
)


display(
    core_dbi_stability_summary
)

,indicator,international_validation,vietnam_validation,international_shap,vietnam_shap
0,emotional_exhaustion,True,True,True,False
1,daily_screen_time,True,True,True,True
2,social_media_hours,True,True,True,True
3,doomscrolling_duration,True,True,True,True
4,late_night_device_usage,True,True,True,True
5,notification_count,True,True,True,True
6,smartphone_unlocks,True,True,True,True
7,app_switch_frequency,True,True,True,True
8,concentration_score,True,True,True,True
9,distraction_frequency,True,True,True,True
10,focus_sessions,True,True,True,True
11,deep_work_hours,True,True,True,True
12,task_completion_rate,True,True,True,True
13,motivation_level,True,True,True,True
14,sleep_hours,True,True,True,True
15,sleep_quality,True,True,True,True

In [21]:
# Tính tổng số bằng chứng hỗ trợ cho từng Core Indicator

core_dbi_stability_summary["evidence_count"] = (
    core_dbi_stability_summary[
        [
            "international_validation",
            "vietnam_validation",
            "international_shap",
            "vietnam_shap"
        ]
    ]
    .sum(axis=1)
)


display(
    core_dbi_stability_summary
)

,indicator,international_validation,vietnam_validation,international_shap,vietnam_shap,evidence_count
0,emotional_exhaustion,True,True,True,False,3
1,daily_screen_time,True,True,True,True,4
2,social_media_hours,True,True,True,True,4
3,doomscrolling_duration,True,True,True,True,4
4,late_night_device_usage,True,True,True,True,4
5,notification_count,True,True,True,True,4
6,smartphone_unlocks,True,True,True,True,4
7,app_switch_frequency,True,True,True,True,4
8,concentration_score,True,True,True,True,4
9,distraction_frequency,True,True,True,True,4
10,focus_sessions,True,True,True,True,4
11,deep_work_hours,True,True,True,True,4
12,task_completion_rate,True,True,True,True,4
13,motivation_level,True,True,True,True,4
14,sleep_hours,True,True,True,True,4
15,sleep_quality,True,True,True,True,4

In [22]:
# Thống kê số lượng indicator theo mức độ bằng chứng

core_evidence_summary = (
    core_dbi_stability_summary
    .groupby("evidence_count")
    .agg(
        indicator_count=("indicator", "count")
    )
    .reset_index()
)


display(
    core_evidence_summary
)

   evidence_count  indicator_count
0               3                1
1               4               15

Kết quả đánh giá độ ổn định của Core DBI Framework cho thấy 16 indicator được xác định là các thành phần có khả năng tổng quát hóa giữa International Dataset và Vietnam Dataset.

Tất cả Core Indicator đều đạt điều kiện xuất hiện trong cả hai bộ dữ liệu và được xác nhận thông qua Feature Validation, cho thấy các indicator này có mối liên hệ đáng kể với trạng thái Digital Burnout trong hai bối cảnh nghiên cứu khác nhau.

Bên cạnh Feature Validation, kết quả SHAP Feature Importance tiếp tục cung cấp bằng chứng về vai trò giải thích của các indicator trong mô hình dự đoán. Phần lớn Core Indicator nhận được sự hỗ trợ từ SHAP ở cả hai dataset, đặc biệt là các nhóm indicator liên quan đến Digital Exposure, Cognitive Performance và Sleep & Recovery.

Riêng indicator emotional_exhaustion chỉ nhận được bằng chứng SHAP từ International Dataset nhưng vẫn được giữ lại trong Core DBI Framework do có sự xác nhận mạnh từ Feature Validation ở cả hai dataset và có vai trò quan trọng trong nhóm Psychological Symptoms.

Nhìn chung, Core DBI Framework gồm 16 indicator được xem là tập chỉ số ổn định, có khả năng đại diện cho các khía cạnh chính của Digital Burnout và có thể sử dụng làm nền tảng để xây dựng hệ thống đánh giá DBI trên nhiều nhóm đối tượng khác nhau.

# 2. Model Performance Comparison

So sánh hiệu quả của các mô hình Machine Learning đã được huấn luyện trên International Dataset và Vietnam Dataset trong bài toán dự đoán Digital Burnout.

Phần này nhằm đánh giá mức độ khác biệt về khả năng dự đoán của mô hình khi áp dụng trên hai bối cảnh dữ liệu khác nhau.

Các mô hình được so sánh dựa trên kết quả huấn luyện đã thực hiện trước đó.

Do kết quả đánh giá của hai dataset được lưu với các chỉ số khác nhau, các metric chung được chuẩn hóa trước khi thực hiện so sánh.

Các chỉ số được sử dụng gồm:

- Accuracy.
- Precision.
- Recall.
- F1-score.

ROC-AUC chỉ được sử dụng trong phân tích riêng đối với International Dataset do Vietnam Dataset không lưu kết quả ROC-AUC trong quá trình đánh giá mô hình.

## 2.1 Load Model Evaluation Results

Tải kết quả đánh giá của các mô hình Machine Learning đã được huấn luyện trên International Dataset và Vietnam Dataset để phục vụ quá trình so sánh hiệu suất dự đoán Digital Burnout.

Các kết quả được sử dụng trong phần này được lấy trực tiếp từ quá trình Modeling trước đó.

Các file đầu vào bao gồm:

- `model_performance.csv`:
  - Chứa các chỉ số đánh giá tổng hợp của từng mô hình.
  - Được sử dụng làm nguồn dữ liệu chính để so sánh hiệu suất.
- `classification_reports.joblib`: Chứa báo cáo phân loại chi tiết của từng mô hình.
- `confusion_matrices.joblib`: Chứa ma trận nhầm lẫn phục vụ phân tích lỗi dự đoán.

Notebook này không thực hiện lại quá trình huấn luyện hoặc đánh giá mô hình.

In [23]:
# Import thư viện cần thiết để đọc file joblib

import joblib

In [24]:
# Đọc kết quả đánh giá mô hình của International Dataset

international_model_performance = pd.read_csv(
    international_models_path / "model_performance.csv"
)


international_classification_reports = joblib.load(
    international_models_path / "classification_reports.joblib"
)


international_confusion_matrices = joblib.load(
    international_models_path / "confusion_matrices.joblib"
)

In [25]:
# Đọc kết quả đánh giá mô hình của Vietnam Dataset

vietnam_model_performance = pd.read_csv(
    vietnam_models_path / "model_performance.csv"
)


vietnam_classification_reports = joblib.load(
    vietnam_models_path / "classification_reports.joblib"
)


vietnam_confusion_matrices = joblib.load(
    vietnam_models_path / "confusion_matrices.joblib"
)

In [26]:
# Kiểm tra cấu trúc kết quả đánh giá mô hình

print(
    f"Số lượng mô hình International Dataset: {international_model_performance.shape[0]}"
)

print(
    f"Số lượng mô hình Vietnam Dataset: {vietnam_model_performance.shape[0]}"
)

Số lượng mô hình International Dataset: 5
Số lượng mô hình Vietnam Dataset: 5

In [27]:
# Hiển thị kết quả đánh giá mô hình

display(
    international_model_performance
)


display(
    vietnam_model_performance
)

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,Training Time (s)
0,Stacking Classifier,0.704569,0.705856,0.704569,0.701706,0.827049,849.281180
1,Logistic Regression,0.704393,0.707062,0.704393,0.700649,0.826605,23.094650
2,XGBoost,0.704157,0.707595,0.704157,0.699887,0.825629,17.116192
3,Voting Classifier,0.704109,0.709070,0.704109,0.698947,0.825908,182.723582
4,Random Forest,0.693813,0.704387,0.693813,0.684896,0.813894,123.896626

,Model,Accuracy,Macro Precision,Macro Recall,Macro F1-score,Weighted F1-score
0,Voting Classifier,0.714286,0.774713,0.441379,0.464394,0.661920
1,XGBoost,0.642857,0.517094,0.406553,0.418077,0.612123
2,Logistic Regression,0.663265,0.372487,0.419569,0.388270,0.574410
3,Random Forest,0.693878,0.444288,0.389190,0.380342,0.627028
4,Stacking Classifier,0.704082,0.484043,0.373813,0.350215,0.612333

Kết quả đánh giá mô hình từ hai dataset đã được tải thành công.

Đối với International Dataset, kết quả đánh giá bao gồm các chỉ số Accuracy, Precision, Recall, F1-score và ROC-AUC được tính trực tiếp trên tập validation.

Đối với Vietnam Dataset, kết quả đánh giá sử dụng thêm các chỉ số Macro và Weighted nhằm phản ánh tốt hơn hiệu quả dự đoán trong bối cảnh dữ liệu khảo sát sinh viên có sự khác biệt về phân bố nhãn.

Sự khác biệt trong cách biểu diễn metric giữa hai dataset cần được chuẩn hóa trước khi thực hiện Comparative Analysis nhằm đảm bảo tính nhất quán trong quá trình so sánh hiệu suất mô hình.

## 2.2 International vs Vietnam Model Performance Comparison

So sánh hiệu suất của các mô hình Machine Learning trên hai bộ dữ liệu International Dataset và Vietnam Dataset nhằm đánh giá khả năng thích nghi của mô hình trong các bối cảnh dữ liệu khác nhau.

Phần này tập trung trả lời các câu hỏi:

- Các mô hình có duy trì hiệu suất tương tự trên hai bộ dữ liệu hay không?
- Dataset quốc tế và dataset sinh viên Việt Nam có tạo ra sự khác biệt về hiệu quả dự đoán hay không?
- Mô hình nào có khả năng tổng quát hóa tốt hơn giữa các môi trường dữ liệu?

### 2.2.1 Chuẩn hóa Model Performance Table

Chuẩn hóa bảng kết quả đánh giá mô hình của International Dataset và Vietnam Dataset về cùng một cấu trúc metric nhằm đảm bảo tính nhất quán trong quá trình so sánh.

Hai dataset sử dụng cách lưu kết quả đánh giá khác nhau:

- International Dataset:
  - Precision
  - Recall
  - F1 Score

- Vietnam Dataset:
  - Macro Precision
  - Macro Recall
  - Macro F1-score

Do đó, các metric của Vietnam Dataset được ánh xạ về cùng tên chuẩn:

- Macro Precision → Precision
- Macro Recall → Recall
- Macro F1-score → F1_score

ROC AUC không được sử dụng trong bảng so sánh chung vì chỉ xuất hiện trong kết quả đánh giá của International Dataset.

In [28]:
# Sao chép bảng kết quả đánh giá mô hình để thực hiện chuẩn hóa

international_comparison = (
    international_model_performance
    .copy()
)


vietnam_comparison = (
    vietnam_model_performance
    .copy()
)

In [29]:
# Chuẩn hóa tên metric của International Dataset

international_comparison = (
    international_comparison
    .rename(
        columns={
            "F1 Score": "F1_score"
        }
    )
)

In [30]:
# Chuẩn hóa tên metric của Vietnam Dataset

vietnam_comparison = (
    vietnam_comparison
    .rename(
        columns={
            "Macro Precision": "Precision",
            "Macro Recall": "Recall",
            "Macro F1-score": "F1_score"
        }
    )
)

In [31]:
# Kiểm tra cấu trúc bảng sau khi chuẩn hóa

print("Các cột của International Dataset:")
print(
    international_comparison.columns.tolist()
)


print("Các cột của Vietnam Dataset:")
print(
    vietnam_comparison.columns.tolist()
)

Các cột của International Dataset:
['Model', 'Accuracy', 'Precision', 'Recall', 'F1_score', 'ROC AUC', 'Training Time (s)']
Các cột của Vietnam Dataset:
['Model', 'Accuracy', 'Precision', 'Recall', 'F1_score', 'Weighted F1-score']

### 2.2.2 Thêm thông tin Dataset

Bổ sung thông tin nguồn dữ liệu để phân biệt kết quả đánh giá của từng dataset trong quá trình phân tích so sánh.

Sau khi chuẩn hóa metric, mỗi bảng kết quả được thêm thuộc tính `Dataset` nhằm xác định bối cảnh dữ liệu sử dụng trong quá trình đánh giá mô hình.

In [32]:
# Gắn nhãn dataset cho kết quả International Dataset

international_comparison["Dataset"] = (
    "International Dataset"
)


# Gắn nhãn dataset cho kết quả Vietnam Dataset

vietnam_comparison["Dataset"] = (
    "Vietnam Dataset"
)

### 2.2.3 Kết hợp kết quả hai Dataset

Tạo bảng dữ liệu thống nhất phục vụ việc so sánh hiệu suất của cùng một mô hình trên hai bộ dữ liệu khác nhau.

Hai bảng kết quả sau chuẩn hóa được ghép lại theo chiều dọc.

Các metric sử dụng trong phân tích:

- Accuracy.
- Precision.
- Recall.
- F1-score.

In [33]:
# Kết hợp kết quả đánh giá mô hình giữa hai dataset

model_performance_comparison = pd.concat(
    [
        international_comparison[
            [
                "Model",
                "Dataset",
                "Accuracy",
                "Precision",
                "Recall",
                "F1_score"
            ]
        ],
        vietnam_comparison[
            [
                "Model",
                "Dataset",
                "Accuracy",
                "Precision",
                "Recall",
                "F1_score"
            ]
        ]
    ],
    ignore_index=True
)


display(
    model_performance_comparison
)

,Model,Dataset,Accuracy,Precision,Recall,F1_score
0,Stacking Classifier,International Dataset,0.704569,0.705856,0.704569,0.701706
1,Logistic Regression,International Dataset,0.704393,0.707062,0.704393,0.700649
2,XGBoost,International Dataset,0.704157,0.707595,0.704157,0.699887
3,Voting Classifier,International Dataset,0.704109,0.709070,0.704109,0.698947
4,Random Forest,International Dataset,0.693813,0.704387,0.693813,0.684896
5,Voting Classifier,Vietnam Dataset,0.714286,0.774713,0.441379,0.464394
6,XGBoost,Vietnam Dataset,0.642857,0.517094,0.406553,0.418077
7,Logistic Regression,Vietnam Dataset,0.663265,0.372487,0.419569,0.388270
8,Random Forest,Vietnam Dataset,0.693878,0.444288,0.389190,0.380342
9,Stacking Classifier,Vietnam Dataset,0.704082,0.484043,0.373813,0.350215

Bảng kết quả sau chuẩn hóa cho phép thực hiện so sánh trực tiếp hiệu suất của các mô hình Machine Learning trên hai bộ dữ liệu.

Do sự khác biệt về cách xây dựng bộ dữ liệu và phân bố nhãn Digital Burnout, hiệu suất của cùng một mô hình có sự thay đổi giữa International Dataset và Vietnam Dataset.

International Dataset cho thấy các mô hình có hiệu suất tương đối đồng đều, với Stacking Classifier, Logistic Regression và XGBoost đạt kết quả gần tương đương trên các chỉ số Accuracy, Precision, Recall và F1-score.

Trong khi đó, Vietnam Dataset có sự khác biệt lớn hơn giữa các mô hình. Voting Classifier đạt Accuracy cao nhất nhưng có sự chênh lệch giữa Precision và Recall, cho thấy khả năng nhận diện các nhóm Digital Burnout chưa hoàn toàn cân bằng.

Kết quả này cho thấy việc áp dụng mô hình trên dữ liệu sinh viên Việt Nam cần được xem xét trong bối cảnh đặc thù về quy mô dữ liệu và phân bố trạng thái Digital Burnout.

## 2.3 Model Performance Ranking Comparison

Đánh giá và xếp hạng hiệu suất của các mô hình Machine Learning trên hai bộ dữ liệu International Dataset và Vietnam Dataset.

Phần này nhằm xác định:

- Mô hình có hiệu suất tốt nhất trên từng bộ dữ liệu.
- Sự khác biệt về thứ hạng mô hình giữa dữ liệu quốc tế và dữ liệu sinh viên Việt Nam.
- Mức độ ổn định của các mô hình khi áp dụng trên các bối cảnh dữ liệu khác nhau.

Sau khi thực hiện so sánh trực tiếp hiệu suất mô hình ở Section 2.2, phần này tiến hành xây dựng bảng xếp hạng dựa trên điểm đánh giá tổng hợp.

Do hai dataset có sự khác biệt về cách đánh giá mô hình, một tiêu chí chung được xây dựng dựa trên các metric xuất hiện ở cả hai dataset:

- Accuracy.
- Recall.
- F1-score.

Điểm đánh giá tổng hợp được sử dụng để xếp hạng từng mô hình trên từng dataset.

### 2.3.1. Xây dựng tiêu chí xếp hạng mô hình

Xây dựng một tiêu chí đánh giá tổng hợp để xếp hạng các mô hình Machine Learning trên hai bộ dữ liệu International Dataset và Vietnam Dataset.

Do hai bộ dữ liệu có sự khác biệt về cách lưu trữ kết quả đánh giá mô hình:

- International Dataset bao gồm thêm ROC-AUC và Training Time.
- Vietnam Dataset bao gồm thêm Weighted F1-score.

Các chỉ số này không xuất hiện đồng thời trên cả hai dataset, do đó không được sử dụng trong tiêu chí xếp hạng chung.

Ba chỉ số được lựa chọn để xây dựng điểm đánh giá tổng hợp gồm:

- Accuracy.
- Recall.
- F1-score.

Trong đó:

- Accuracy phản ánh khả năng dự đoán đúng tổng thể của mô hình.
- Recall được ưu tiên nhằm đánh giá khả năng phát hiện đúng các trường hợp có nguy cơ Digital Burnout.
- F1-score đảm bảo sự cân bằng giữa Precision và Recall.

Công thức điểm xếp hạng:

$$
Ranking\ Score =
0.4 \times Accuracy
+
0.3 \times Recall
+
0.3 \times F1\text{-}score
$$

Trọng số được thiết kế nhằm ưu tiên khả năng dự đoán tổng thể nhưng vẫn duy trì sự cân bằng giữa khả năng nhận diện và độ chính xác.

In [34]:
# Tính điểm đánh giá tổng hợp cho từng mô hình

model_performance_comparison["ranking_score"] = (
    0.4 * model_performance_comparison["Accuracy"]
    +
    0.3 * model_performance_comparison["Recall"]
    +
    0.3 * model_performance_comparison["F1_score"]
)


# Hiển thị kết quả sau khi tính ranking score

display(
    model_performance_comparison
)

,Model,Dataset,Accuracy,Precision,Recall,F1_score,ranking_score
0,Stacking Classifier,International Dataset,0.704569,0.705856,0.704569,0.701706,0.703710
1,Logistic Regression,International Dataset,0.704393,0.707062,0.704393,0.700649,0.703270
2,XGBoost,International Dataset,0.704157,0.707595,0.704157,0.699887,0.702876
3,Voting Classifier,International Dataset,0.704109,0.709070,0.704109,0.698947,0.702560
4,Random Forest,International Dataset,0.693813,0.704387,0.693813,0.684896,0.691138
5,Voting Classifier,Vietnam Dataset,0.714286,0.774713,0.441379,0.464394,0.557446
6,XGBoost,Vietnam Dataset,0.642857,0.517094,0.406553,0.418077,0.504532
7,Logistic Regression,Vietnam Dataset,0.663265,0.372487,0.419569,0.388270,0.507658
8,Random Forest,Vietnam Dataset,0.693878,0.444288,0.389190,0.380342,0.508411
9,Stacking Classifier,Vietnam Dataset,0.704082,0.484043,0.373813,0.350215,0.498841

Điểm đánh giá tổng hợp đã được xây dựng thành công cho toàn bộ mô hình trên hai bộ dữ liệu nghiên cứu.

Kết quả cho thấy hiệu suất mô hình có sự khác biệt giữa International Dataset và Vietnam Dataset.

Đối với International Dataset, các mô hình đạt điểm xếp hạng tương đối đồng đều. Stacking Classifier đạt giá trị ranking score cao nhất, tiếp theo là Logistic Regression và XGBoost. Điều này cho thấy các mô hình có khả năng khai thác tốt mối quan hệ giữa các đặc trưng hành vi số và trạng thái Digital Burnout trong bộ dữ liệu có quy mô lớn.

Đối với Vietnam Dataset, ranking score của các mô hình thấp hơn so với International Dataset. Voting Classifier đạt kết quả cao nhất theo tiêu chí tổng hợp, tuy nhiên khoảng cách giữa các mô hình không quá lớn. Sự suy giảm hiệu suất này có thể xuất phát từ đặc điểm của bộ dữ liệu khảo sát sinh viên Việt Nam với kích thước mẫu nhỏ hơn và sự khác biệt về phân bố hành vi sử dụng thiết bị số.

Kết quả ranking score sẽ được sử dụng ở bước tiếp theo để xếp hạng mô hình theo từng dataset và đánh giá mức độ ổn định của các phương pháp Machine Learning.

### 2.3.2 Xếp hạng mô hình theo từng Dataset

Xác định thứ hạng của các mô hình Machine Learning trên từng bộ dữ liệu dựa trên điểm đánh giá tổng hợp đã được xây dựng ở phần trước.

Sau khi tính toán `ranking_score`, các mô hình được xếp hạng riêng biệt theo từng dataset.

Việc xếp hạng theo từng dataset giúp:

- Xác định mô hình có hiệu suất tốt nhất trong từng bối cảnh dữ liệu.
- Đánh giá sự khác biệt về khả năng thích nghi của mô hình giữa International Dataset và Vietnam Dataset.
- Tránh việc so sánh trực tiếp các mô hình giữa hai dataset có đặc điểm dữ liệu khác nhau.

In [35]:
# Xếp hạng mô hình theo từng dataset dựa trên ranking score

model_ranking = (
    model_performance_comparison
    .sort_values(
        by=[
            "Dataset",
            "ranking_score"
        ],
        ascending=[
            True,
            False
        ]
    )
    .copy()
)


# Gán thứ hạng mô hình trong từng dataset

model_ranking["Rank"] = (
    model_ranking
    .groupby("Dataset")["ranking_score"]
    .rank(
        method="dense",
        ascending=False
    )
    .astype(int)
)


# Sắp xếp lại thứ tự cột hiển thị

model_ranking = (
    model_ranking
    [
        [
            "Dataset",
            "Rank",
            "Model",
            "ranking_score",
            "Accuracy",
            "Recall",
            "F1_score"
        ]
    ]
)


display(
    model_ranking
)

,Dataset,Rank,Model,ranking_score,Accuracy,Recall,F1_score
0,International Dataset,1,Stacking Classifier,0.703710,0.704569,0.704569,0.701706
1,International Dataset,2,Logistic Regression,0.703270,0.704393,0.704393,0.700649
2,International Dataset,3,XGBoost,0.702876,0.704157,0.704157,0.699887
3,International Dataset,4,Voting Classifier,0.702560,0.704109,0.704109,0.698947
4,International Dataset,5,Random Forest,0.691138,0.693813,0.693813,0.684896
5,Vietnam Dataset,1,Voting Classifier,0.557446,0.714286,0.441379,0.464394
8,Vietnam Dataset,2,Random Forest,0.508411,0.693878,0.389190,0.380342
7,Vietnam Dataset,3,Logistic Regression,0.507658,0.663265,0.419569,0.388270
6,Vietnam Dataset,4,XGBoost,0.504532,0.642857,0.406553,0.418077
9,Vietnam Dataset,5,Stacking Classifier,0.498841,0.704082,0.373813,0.350215

Kết quả xếp hạng cho thấy thứ tự ưu tiên của các mô hình có sự khác biệt giữa hai bộ dữ liệu.

Trên International Dataset, Stacking Classifier đạt ranking score cao nhất, cho thấy khả năng kết hợp các mô hình thành phần giúp cải thiện hiệu quả dự đoán trong bộ dữ liệu có quy mô lớn. Logistic Regression và XGBoost cũng đạt kết quả gần tương đương, phản ánh tính ổn định của các phương pháp này trong việc khai thác các đặc trưng Digital Burnout.

Trên Vietnam Dataset, Voting Classifier đạt thứ hạng cao nhất theo tiêu chí tổng hợp. Tuy nhiên, ranking score của toàn bộ mô hình thấp hơn so với International Dataset, cho thấy việc dự đoán Digital Burnout trên dữ liệu sinh viên Việt Nam gặp nhiều thách thức hơn do kích thước mẫu nhỏ và sự khác biệt về đặc điểm hành vi.

Sự khác biệt về mô hình đứng đầu giữa hai dataset cho thấy không có một mô hình duy nhất tối ưu cho mọi bối cảnh dữ liệu. Hiệu suất mô hình phụ thuộc vào đặc điểm phân bố dữ liệu, quy mô mẫu và cấu trúc đặc trưng đầu vào.

### 2.3.5 So sánh mức độ ổn định giữa 2 dataset

Đánh giá mức độ ổn định của các mô hình Machine Learning khi được áp dụng trên hai bộ dữ liệu có đặc điểm khác nhau.

Sau khi xếp hạng mô hình riêng trên từng dataset, phần này tiến hành so sánh sự thay đổi thứ hạng của các mô hình giữa International Dataset và Vietnam Dataset.

Một mô hình được xem là có mức độ ổn định cao khi:

- Duy trì thứ hạng tốt trên cả hai dataset.
- Có điểm đánh giá tổng hợp không giảm quá lớn khi chuyển đổi bối cảnh dữ liệu.
- Có khả năng thích nghi với sự khác biệt về quy mô mẫu và đặc điểm hành vi của người tham gia khảo sát.

Phân tích này giúp xác định liệu mô hình có khả năng tổng quát hóa tốt hay chỉ hoạt động hiệu quả trên một bộ dữ liệu cụ thể.

In [37]:
# Tạo bảng so sánh thứ hạng mô hình giữa hai dataset

model_rank_comparison = (
    model_ranking
    .pivot(
        index="Model",
        columns="Dataset",
        values="Rank"
    )
    .reset_index()
)


# Tính sự thay đổi thứ hạng giữa hai dataset

model_rank_comparison["Rank_Change"] = (
    abs(
        model_rank_comparison["International Dataset"]
        -
        model_rank_comparison["Vietnam Dataset"]
    )
)


# Sắp xếp theo mức thay đổi thứ hạng tăng dần

model_rank_comparison = (
    model_rank_comparison
    .sort_values(
        by="Rank_Change",
        ascending=True
    )
    .reset_index(drop=True)
)


display(
    model_rank_comparison
)

Dataset,Model,International Dataset,Vietnam Dataset,Rank_Change
0,Logistic Regression,2,3,1
1,XGBoost,3,4,1
2,Voting Classifier,4,1,3
3,Random Forest,5,2,3
4,Stacking Classifier,1,5,4

Kết quả so sánh mức độ thay đổi thứ hạng cho thấy sự khác biệt đáng kể về khả năng thích nghi của các mô hình giữa hai bộ dữ liệu.

Logistic Regression và XGBoost có mức thay đổi thứ hạng thấp nhất với Rank Change bằng 1. Điều này cho thấy hai mô hình duy trì hiệu suất tương đối ổn định khi chuyển đổi từ International Dataset sang Vietnam Dataset.

Voting Classifier cải thiện đáng kể trên Vietnam Dataset khi tăng từ vị trí thứ 4 trên International Dataset lên vị trí thứ 1. Kết quả này cho thấy cơ chế kết hợp nhiều mô hình thành phần có thể phù hợp hơn với dữ liệu khảo sát có quy mô nhỏ và đặc điểm hành vi riêng biệt.

Ngược lại, Stacking Classifier có sự thay đổi thứ hạng lớn nhất, từ vị trí thứ 1 trên International Dataset xuống vị trí thứ 5 trên Vietnam Dataset. Điều này cho thấy mặc dù mô hình đạt hiệu quả cao trên bộ dữ liệu lớn, khả năng tổng quát hóa có thể bị ảnh hưởng khi áp dụng trên dữ liệu nhỏ hơn.

Nhìn chung, Logistic Regression và XGBoost thể hiện tính ổn định cao hơn giữa hai bối cảnh dữ liệu, trong khi Voting Classifier có khả năng thích nghi tốt với dữ liệu sinh viên Việt Nam.

# 3. Feature Importance Comparison

So sánh mức độ quan trọng của các indicator DBI giữa International Dataset và Vietnam Dataset nhằm đánh giá sự nhất quán của bộ chỉ số Digital Burnout Indicator (DBI) sau quá trình refinement.

Phần này nhằm trả lời các câu hỏi:

- Các indicator nào được cả hai dataset xác nhận có vai trò quan trọng?
- Các đặc trưng nào chỉ phù hợp với từng bối cảnh dữ liệu riêng biệt?
- Bộ DBI Core Indicator có nhận được sự hỗ trợ từ kết quả Machine Learning hay không?

Sau khi hoàn thiện quá trình xây dựng và xác thực DBI ở Notebook 1, phần này sử dụng kết quả Feature Validation và SHAP Feature Importance từ hai mô hình đã được huấn luyện trên từng dataset.

Hai nguồn bằng chứng được sử dụng:

**Feature Validation**

Đánh giá mức độ liên quan thống kê và khả năng phân biệt nhóm Digital Burnout thông qua:

- ANOVA Feature Selection.
- Random Forest Feature Importance.

**SHAP Feature Importance**

Đánh giá mức độ đóng góp của từng indicator trong quá trình dự đoán của mô hình Machine Learning.

## 3.1. Load và Chuẩn hóa Feature Validation Results

Đọc và chuẩn hóa kết quả Feature Validation của International Dataset và Vietnam Dataset để tạo nguồn dữ liệu thống nhất phục vụ quá trình so sánh mức độ quan trọng của các indicator DBI.

Trong quá trình xây dựng DBI Framework, hai bộ dữ liệu được phân tích độc lập nên kết quả Feature Validation được lưu trữ với cấu trúc khác nhau.

International Dataset sử dụng các thông tin:

- F-score.
- P-value.
- Feature Importance từ Random Forest.
- ANOVA Rank.
- Random Forest Rank.
- Trạng thái feature.

Vietnam Dataset sử dụng các thông tin:

- F-Statistic.
- P-value.
- Feature Importance.
- ANOVA Rank.
- Random Forest Rank.
- Trạng thái feature.

Do sự khác biệt trong cách đặt tên cột, bước này thực hiện:

1. Đọc hai file `validated_features.csv`.
2. Chuẩn hóa tên cột về cùng một cấu trúc.
3. Giữ lại các thông tin cần thiết cho quá trình comparative analysis.

Cấu trúc chuẩn sau khi xử lý:

- `indicator`: tên indicator DBI.
- `importance`: mức độ quan trọng của indicator.
- `validation_status`: trạng thái xác nhận feature.
- `dataset`: nguồn dữ liệu.

In [40]:
import os

# Đọc kết quả Feature Validation của International Dataset

international_validation = pd.read_csv(
    os.path.join(
        project_path,
        "data",
        "processed",
        "international_dataset",
        "validated_features.csv"
    )
)


# Đọc kết quả Feature Validation của Vietnam Dataset

vietnam_validation = pd.read_csv(
    os.path.join(
        project_path,
        "data",
        "processed",
        "vietnam_dataset",
        "validated_features.csv"
    )
)


# Hiển thị kết quả Feature Validation

display(
    international_validation.head()
)


display(
    vietnam_validation.head()
)

,feature,f_score,p_value,significant,importance,rf_rank,anova_rank,rank_difference,feature_status
0,emotional_exhaustion,693837.690271,0.0,True,0.227302,1,1,0,Core Feature
1,stress_level,339866.544911,0.0,True,0.135371,2,2,0,Core Feature
2,daily_screen_time,101564.936783,0.0,True,0.067815,3,4,1,Core Feature
3,work_satisfaction,137327.575101,0.0,True,0.065593,4,3,1,Core Feature
4,doomscrolling_duration,83030.435719,0.0,True,0.054545,5,5,0,Core Feature

,Feature,F-Statistic,P-Value,Importance,ANOVA_Rank,RF_Rank,Average_Rank,feature_status
0,digital_exhaustion,77.528278,6.289798e-31,0.099671,1.0,2.0,1.5,Core Feature
1,digital_stress,74.983400,4.944099e-30,0.085296,2.0,3.0,2.5,Core Feature
2,performance_decline,70.502365,1.926286e-28,0.079153,3.0,5.0,4.0,Core Feature
3,physical_fatigue,61.058877,4.973406e-25,0.082970,4.0,4.0,4.0,Core Feature
4,loss_of_interest,31.369879,9.848678e-14,0.108078,7.0,1.0,4.0,Core Feature

In [41]:
# Chuẩn hóa tên cột của International Dataset

international_validation_clean = (
    international_validation
    .rename(
        columns={
            "feature": "indicator",
            "significant": "validation_status"
        }
    )
    [
        [
            "indicator",
            "importance",
            "validation_status"
        ]
    ]
    .copy()
)


# Thêm thông tin dataset

international_validation_clean["dataset"] = (
    "International Dataset"
)


# Chuẩn hóa tên cột của Vietnam Dataset

vietnam_validation_clean = (
    vietnam_validation
    .rename(
        columns={
            "Feature": "indicator",
            "feature_status": "validation_status"
        }
    )
    [
        [
            "indicator",
            "Importance",
            "validation_status"
        ]
    ]
    .rename(
        columns={
            "Importance": "importance"
        }
    )
    .copy()
)


# Thêm thông tin dataset

vietnam_validation_clean["dataset"] = (
    "Vietnam Dataset"
)


# Hiển thị kết quả sau chuẩn hóa

display(
    international_validation_clean.head()
)


display(
    vietnam_validation_clean.head()
)

,indicator,importance,validation_status,dataset
0,emotional_exhaustion,0.227302,True,International Dataset
1,stress_level,0.135371,True,International Dataset
2,daily_screen_time,0.067815,True,International Dataset
3,work_satisfaction,0.065593,True,International Dataset
4,doomscrolling_duration,0.054545,True,International Dataset

             indicator  importance validation_status          dataset
0   digital_exhaustion    0.099671      Core Feature  Vietnam Dataset
1       digital_stress    0.085296      Core Feature  Vietnam Dataset
2  performance_decline    0.079153      Core Feature  Vietnam Dataset
3     physical_fatigue    0.082970      Core Feature  Vietnam Dataset
4     loss_of_interest    0.108078      Core Feature  Vietnam Dataset

## 3.2. So sánh Feature Validation giữa hai dataset

So sánh kết quả Feature Validation giữa International Dataset và Vietnam Dataset nhằm xác định các indicator có tính nhất quán và các indicator thể hiện sự khác biệt theo từng nhóm dữ liệu.

Sau khi chuẩn hóa cấu trúc dữ liệu, hai bảng Feature Validation được kết hợp dựa trên tên indicator.

Phân tích tập trung vào:

- Indicator được xác nhận ở cả hai dataset.
- Indicator chỉ được xác nhận ở một dataset.
- Mức độ quan trọng của indicator giữa hai bối cảnh dữ liệu.

Kết quả này giúp đánh giá liệu các Core Indicator trong DBI Framework có được hỗ trợ bởi nhiều nguồn dữ liệu độc lập hay không.

In [42]:
# Kết hợp kết quả Feature Validation của hai dataset

feature_validation_comparison = (
    international_validation_clean
    .merge(
        vietnam_validation_clean,
        on="indicator",
        how="outer",
        suffixes=(
            "_international",
            "_vietnam"
        )
    )
)


# Hiển thị kết quả so sánh

display(
    feature_validation_comparison
)

,indicator,importance_international,validation_status_international,dataset_international,importance_vietnam,validation_status_vietnam,dataset_vietnam
0,age,0.020986,False,International Dataset,NaN,NaN,NaN
1,app_switch_frequency,0.025059,False,International Dataset,0.028500,Validated Feature,Vietnam Dataset
2,caffeine_intake,0.011973,False,International Dataset,NaN,NaN,NaN
3,concentration_score,0.013532,False,International Dataset,0.046215,Supporting Feature,Vietnam Dataset
4,daily_screen_time,0.067815,True,International Dataset,0.028639,Validated Feature,Vietnam Dataset
5,deep_work_hours,0.025811,True,International Dataset,0.030252,Supporting Feature,Vietnam Dataset
6,digital_exhaustion,NaN,NaN,NaN,0.099671,Core Feature,Vietnam Dataset
7,digital_stress,NaN,NaN,NaN,0.085296,Core Feature,Vietnam Dataset
8,distraction_frequency,0.045728,True,International Dataset,0.029124,Supporting Feature,Vietnam Dataset
9,doomscrolling_duration,0.054545,True,International Dataset,0.031570,Validated Feature,Vietnam Dataset
10,emotional_exhaustion,0.227302,True,International Dataset,0.074050,Validated Feature,Vietnam Dataset
11,focus_sessions,0.013355,True,International Dataset,0.024264,Supporting Feature,Vietnam Dataset
12,internet_stability,0.013279,False,International Dataset,NaN,NaN,NaN
13,late_night_device_usage,0.020974,True,International Dataset,0.014931,Validated Feature,Vietnam Dataset
14,loss_of_interest,NaN,NaN,NaN,0.108078,Core Feature,Vietnam Dataset
15,meeting_hours,0.021878,False,International Dataset,NaN,NaN,NaN
16,mental_fatigue,0.013462,False,International Dataset,NaN,NaN,NaN
17,motivation_level,0.013400,False,International Dataset,0.046895,Validated Feature,Vietnam Dataset
18,notification_count,0.035040,True,International Dataset,0.028996,Validated Feature,Vietnam Dataset
19,performance_decline,NaN,NaN,NaN,0.079153,Core Feature,Vietnam Dataset
20,physical_activity,0.030053,True,International Dataset,NaN,NaN,NaN
21,physical_fatigue,NaN,NaN,NaN,0.082970,Core Feature,Vietnam Dataset
22,remote_work_days,0.011098,False,International Dataset,NaN,NaN,NaN
23,sleep_hours,0.037063,True,International Dataset,0.034686,Supporting Feature,Vietnam Dataset
24,sleep_quality,0.013424,False,International Dataset,0.045819,Validated Feature,Vietnam Dataset
25,smartphone_unlocks,0.024923,False,International Dataset,0.028974,Supporting Feature,Vietnam Dataset
26,social_media_hours,0.022803,False,International Dataset,0.023870,Supporting Feature,Vietnam Dataset
27,stress_level,0.135371,True,International Dataset,NaN,NaN,NaN
28,task_completion_rate,0.022150,False,International Dataset,0.028045,Supporting Feature,Vietnam Dataset
29,work_satisfaction,0.065593,True,International Dataset,NaN,NaN,NaN
30,workspace_quality,0.013384,False,International Dataset,NaN,NaN,NaN

In [44]:
# Xác định trạng thái validation giữa hai dataset

feature_validation_comparison["international_validated"] = (
    feature_validation_comparison[
        "validation_status_international"
    ]
    == True
)


feature_validation_comparison["vietnam_validated"] = (
    feature_validation_comparison[
        "validation_status_vietnam"
    ]
    .notna()
)


# Xác định trạng thái so sánh

feature_validation_comparison["comparison_status"] = (
    feature_validation_comparison.apply(
        lambda row:
            "Validated on both datasets"
            if (
                row["international_validated"]
                and
                row["vietnam_validated"]
            )
            else
            "International Dataset only"
            if row["international_validated"]
            else
            "Vietnam Dataset only"
            if row["vietnam_validated"]
            else
            "Not validated",
        axis=1
    )
)


display(
    feature_validation_comparison[
        [
            "indicator",
            "international_validated",
            "vietnam_validated",
            "comparison_status"
        ]
    ]
)

,indicator,international_validated,vietnam_validated,comparison_status
0,age,False,False,Not validated
1,app_switch_frequency,False,True,Vietnam Dataset only
2,caffeine_intake,False,False,Not validated
3,concentration_score,False,True,Vietnam Dataset only
4,daily_screen_time,True,True,Validated on both datasets
5,deep_work_hours,True,True,Validated on both datasets
6,digital_exhaustion,False,True,Vietnam Dataset only
7,digital_stress,False,True,Vietnam Dataset only
8,distraction_frequency,True,True,Validated on both datasets
9,doomscrolling_duration,True,True,Validated on both datasets
10,emotional_exhaustion,True,True,Validated on both datasets
11,focus_sessions,True,True,Validated on both datasets
12,internet_stability,False,False,Not validated
13,late_night_device_usage,True,True,Validated on both datasets
14,loss_of_interest,False,True,Vietnam Dataset only
15,meeting_hours,False,False,Not validated
16,mental_fatigue,False,False,Not validated
17,motivation_level,False,True,Vietnam Dataset only
18,notification_count,True,True,Validated on both datasets
19,performance_decline,False,True,Vietnam Dataset only
20,physical_activity,True,False,International Dataset only
21,physical_fatigue,False,True,Vietnam Dataset only
22,remote_work_days,False,False,Not validated
23,sleep_hours,True,True,Validated on both datasets
24,sleep_quality,False,True,Vietnam Dataset only
25,smartphone_unlocks,False,True,Vietnam Dataset only
26,social_media_hours,False,True,Vietnam Dataset only
27,stress_level,True,False,International Dataset only
28,task_completion_rate,False,True,Vietnam Dataset only
29,work_satisfaction,True,False,International Dataset only
30,workspace_quality,False,False,Not validated

In [45]:
# Thống kê số lượng indicator theo trạng thái so sánh

validation_summary = (
    feature_validation_comparison
    [
        "comparison_status"
    ]
    .value_counts()
    .reset_index()
)


validation_summary.columns = [
    "comparison_status",
    "indicator_count"
]


display(
    validation_summary
)

            comparison_status  indicator_count
0        Vietnam Dataset only               12
1  Validated on both datasets                9
2               Not validated                7
3  International Dataset only                3

Kết quả Feature Validation Comparison cho thấy mức độ xác nhận của các indicator DBI có sự khác biệt giữa hai bộ dữ liệu.

Trong tổng số 31 indicator được đánh giá:

- 9 indicator được xác nhận trên cả International Dataset và Vietnam Dataset.
- 12 indicator chỉ được xác nhận trên Vietnam Dataset.
- 3 indicator chỉ được xác nhận trên International Dataset.
- 7 indicator chưa được xác nhận trên cả hai bộ dữ liệu.

Nhóm indicator được xác nhận trên cả hai dataset thể hiện mức độ ổn định cao và có khả năng phản ánh các đặc điểm chung của Digital Burnout trong nhiều bối cảnh nghiên cứu. Đây là nhóm bằng chứng quan trọng để củng cố các Core Indicator trong DBI Framework.

Ngược lại, số lượng indicator được xác nhận riêng trên Vietnam Dataset cao hơn International Dataset cho thấy bộ dữ liệu sinh viên Việt Nam có một số biểu hiện Digital Burnout đặc thù. Các indicator này có thể phản ánh sự khác biệt về môi trường học tập, thói quen sử dụng công nghệ và đặc điểm tâm lý của nhóm đối tượng nghiên cứu.

Một số indicator chỉ xuất hiện trên International Dataset phản ánh các yếu tố liên quan đến môi trường làm việc hoặc bối cảnh sử dụng thiết bị chuyên nghiệp, do International Dataset bao gồm nhóm đối tượng rộng hơn.

Nhìn chung, kết quả Feature Validation cho thấy DBI Framework bao gồm hai nhóm thành phần:
- Core Indicator: các chỉ số có tính nhất quán cao giữa hai dataset.
- Dataset-specific Indicator: các chỉ số phản ánh đặc điểm riêng của từng nhóm nghiên cứu.

## 3.3 So sánh SHAP Feature Importance giữa hai Dataset

So sánh mức độ đóng góp của các indicator DBI trong mô hình Machine Learning giữa International Dataset và Vietnam Dataset thông qua phương pháp SHAP Feature Importance.

SHAP Feature Importance được sử dụng để giải thích vai trò của từng indicator trong quá trình dự đoán Digital Burnout của mô hình.

Khác với Feature Validation chỉ đánh giá mức độ liên quan của feature với target, SHAP cho biết mức độ ảnh hưởng trực tiếp của feature đến kết quả dự đoán của mô hình.

Phân tích này tập trung vào:

- Indicator có mức SHAP importance cao trên từng dataset.
- Sự tương đồng và khác biệt về vai trò của indicator giữa hai mô hình.
- Các indicator có tính ổn định cao trong cả phân tích thống kê và giải thích mô hình.

In [46]:
# Đọc kết quả SHAP Feature Importance của International Dataset

international_shap = pd.read_csv(
    os.path.join(
        project_path,
        "results",
        "international_dataset",
        "shap_feature_importance.csv"
    )
)


# Đọc kết quả SHAP Feature Importance của Vietnam Dataset

vietnam_shap = pd.read_csv(
    os.path.join(
        project_path,
        "results",
        "vietnam_dataset",
        "shap_feature_importance.csv"
    )
)


# Hiển thị dữ liệu SHAP ban đầu

display(
    international_shap.head()
)


display(
    vietnam_shap.head()
)

                  feature  mean_shap  mean_abs_shap
0    emotional_exhaustion  -0.255703       0.761339
1            stress_level  -0.146301       0.565297
2       work_satisfaction  -0.059630       0.365784
3       daily_screen_time  -0.045927       0.293019
4  doomscrolling_duration  -0.036148       0.271082

                             Feature  Mean_SHAP
0    numerical__app_switch_frequency   0.399335
1      numerical__smartphone_unlocks   0.347211
2        numerical__motivation_level   0.333562
3  numerical__doomscrolling_duration   0.297905
4             numerical__sleep_hours   0.278166

In [48]:
# Chuẩn hóa SHAP Importance của International Dataset

international_shap_clean = (
    international_shap
    .rename(
        columns={
            "feature": "indicator",
            "mean_abs_shap": "shap_importance"
        }
    )
    [
        [
            "indicator",
            "shap_importance"
        ]
    ]
    .copy()
)


# Gắn nhãn dataset

international_shap_clean["dataset"] = (
    "International Dataset"
)


# Chuẩn hóa SHAP Importance của Vietnam Dataset

vietnam_shap_clean = (
    vietnam_shap
    .rename(
        columns={
            "Feature": "indicator",
            "Mean_SHAP": "shap_importance"
        }
    )
    [
        [
            "indicator",
            "shap_importance"
        ]
    ]
    .copy()
)


# Gắn nhãn dataset

vietnam_shap_clean["dataset"] = (
    "Vietnam Dataset"
)


# Hiển thị kết quả sau chuẩn hóa

display(
    international_shap_clean.head()
)


display(
    vietnam_shap_clean.head()
)

                indicator  shap_importance                dataset
0    emotional_exhaustion         0.761339  International Dataset
1            stress_level         0.565297  International Dataset
2       work_satisfaction         0.365784  International Dataset
3       daily_screen_time         0.293019  International Dataset
4  doomscrolling_duration         0.271082  International Dataset

                           indicator  shap_importance          dataset
0    numerical__app_switch_frequency         0.399335  Vietnam Dataset
1      numerical__smartphone_unlocks         0.347211  Vietnam Dataset
2        numerical__motivation_level         0.333562  Vietnam Dataset
3  numerical__doomscrolling_duration         0.297905  Vietnam Dataset
4             numerical__sleep_hours         0.278166  Vietnam Dataset

In [52]:
# Loại bỏ tiền tố preprocessing trong Vietnam SHAP

vietnam_shap_clean["indicator"] = (
    vietnam_shap_clean["indicator"]
    .str.replace(
        "numerical__",
        "",
        regex=False
    )
    .str.replace(
        "categorical__",
        "",
        regex=False
    )
)


# Chuẩn hóa tên indicator

international_shap_clean["indicator"] = (
    international_shap_clean["indicator"]
    .str.lower()
    .str.strip()
)


vietnam_shap_clean["indicator"] = (
    vietnam_shap_clean["indicator"]
    .str.lower()
    .str.strip()
)


# Kiểm tra lại indicator

display(
    vietnam_shap_clean.head()
)

                indicator  shap_importance          dataset
0    app_switch_frequency         0.399335  Vietnam Dataset
1      smartphone_unlocks         0.347211  Vietnam Dataset
2        motivation_level         0.333562  Vietnam Dataset
3  doomscrolling_duration         0.297905  Vietnam Dataset
4             sleep_hours         0.278166  Vietnam Dataset

In [53]:
# Kết hợp kết quả SHAP Importance của hai dataset

shap_comparison = (
    international_shap_clean
    .merge(
        vietnam_shap_clean,
        on="indicator",
        how="outer",
        suffixes=(
            "_international",
            "_vietnam"
        )
    )
)


# Hiển thị kết quả so sánh SHAP

display(
    shap_comparison
)

,indicator,shap_importance_international,dataset_international,shap_importance_vietnam,dataset_vietnam
0,age,0.004499,International Dataset,NaN,NaN
1,app_switch_frequency,0.005068,International Dataset,0.399335,Vietnam Dataset
2,caffeine_intake,0.002793,International Dataset,NaN,NaN
3,concentration_score,0.003187,International Dataset,0.249486,Vietnam Dataset
4,daily_screen_time,0.293019,International Dataset,0.214550,Vietnam Dataset
5,deep_work_hours,0.077723,International Dataset,0.205566,Vietnam Dataset
6,distraction_frequency,0.218274,International Dataset,0.196482,Vietnam Dataset
7,doomscrolling_duration,0.271082,International Dataset,0.297905,Vietnam Dataset
8,emotional_exhaustion,0.761339,International Dataset,NaN,NaN
9,focus_sessions,0.002869,International Dataset,0.134085,Vietnam Dataset
10,internet_stability,0.003124,International Dataset,NaN,NaN
11,late_night_device_usage,0.245732,International Dataset,0.211944,Vietnam Dataset
12,meeting_hours,0.004709,International Dataset,NaN,NaN
13,mental_fatigue,0.002593,International Dataset,NaN,NaN
14,motivation_level,0.003209,International Dataset,0.333562,Vietnam Dataset
15,notification_count,0.138617,International Dataset,0.193232,Vietnam Dataset
16,physical_activity,0.149915,International Dataset,NaN,NaN
17,remote_work_days,0.003149,International Dataset,NaN,NaN
18,sleep_hours,0.169751,International Dataset,0.278166,Vietnam Dataset
19,sleep_quality,0.003462,International Dataset,0.216336,Vietnam Dataset
20,smartphone_unlocks,0.006017,International Dataset,0.347211,Vietnam Dataset
21,social_media_hours,0.005106,International Dataset,0.172843,Vietnam Dataset
22,stress_level,0.565297,International Dataset,NaN,NaN
23,task_completion_rate,0.005185,International Dataset,0.170771,Vietnam Dataset
24,work_satisfaction,0.365784,International Dataset,NaN,NaN
25,workspace_quality,0.003168,International Dataset,NaN,NaN

In [54]:
# Xác định indicator có SHAP Importance trên từng dataset

shap_comparison["international_shap_supported"] = (
    shap_comparison[
        "shap_importance_international"
    ]
    .notna()
)


shap_comparison["vietnam_shap_supported"] = (
    shap_comparison[
        "shap_importance_vietnam"
    ]
    .notna()
)


# Xác định mức độ nhất quán SHAP

shap_comparison["shap_consistency_status"] = (
    shap_comparison.apply(
        lambda row:
            "Supported on both datasets"
            if (
                row["international_shap_supported"]
                and
                row["vietnam_shap_supported"]
            )
            else
            "International Dataset only"
            if row["international_shap_supported"]
            else
            "Vietnam Dataset only"
            if row["vietnam_shap_supported"]
            else
            "Not supported",
        axis=1
    )
)


display(
    shap_comparison[
        [
            "indicator",
            "international_shap_supported",
            "vietnam_shap_supported",
            "shap_consistency_status"
        ]
    ]
)

,indicator,international_shap_supported,vietnam_shap_supported,shap_consistency_status
0,age,True,False,International Dataset only
1,app_switch_frequency,True,True,Supported on both datasets
2,caffeine_intake,True,False,International Dataset only
3,concentration_score,True,True,Supported on both datasets
4,daily_screen_time,True,True,Supported on both datasets
5,deep_work_hours,True,True,Supported on both datasets
6,distraction_frequency,True,True,Supported on both datasets
7,doomscrolling_duration,True,True,Supported on both datasets
8,emotional_exhaustion,True,False,International Dataset only
9,focus_sessions,True,True,Supported on both datasets
10,internet_stability,True,False,International Dataset only
11,late_night_device_usage,True,True,Supported on both datasets
12,meeting_hours,True,False,International Dataset only
13,mental_fatigue,True,False,International Dataset only
14,motivation_level,True,True,Supported on both datasets
15,notification_count,True,True,Supported on both datasets
16,physical_activity,True,False,International Dataset only
17,remote_work_days,True,False,International Dataset only
18,sleep_hours,True,True,Supported on both datasets
19,sleep_quality,True,True,Supported on both datasets
20,smartphone_unlocks,True,True,Supported on both datasets
21,social_media_hours,True,True,Supported on both datasets
22,stress_level,True,False,International Dataset only
23,task_completion_rate,True,True,Supported on both datasets
24,work_satisfaction,True,False,International Dataset only
25,workspace_quality,True,False,International Dataset only

In [55]:
# Thống kê số lượng indicator theo mức độ hỗ trợ SHAP

shap_summary = (
    shap_comparison[
        "shap_consistency_status"
    ]
    .value_counts()
    .reset_index()
)


shap_summary.columns = [
    "shap_consistency_status",
    "indicator_count"
]


display(
    shap_summary
)

      shap_consistency_status  indicator_count
0  Supported on both datasets               15
1  International Dataset only               11

In [56]:
# Hiển thị danh sách indicator theo mức độ nhất quán SHAP

display(
    shap_comparison[
        [
            "indicator",
            "shap_consistency_status"
        ]
    ]
    .sort_values(
        by="shap_consistency_status"
    )
)

                  indicator     shap_consistency_status
0                       age  International Dataset only
22             stress_level  International Dataset only
17         remote_work_days  International Dataset only
16        physical_activity  International Dataset only
13           mental_fatigue  International Dataset only
24        work_satisfaction  International Dataset only
10       internet_stability  International Dataset only
8      emotional_exhaustion  International Dataset only
12            meeting_hours  International Dataset only
2           caffeine_intake  International Dataset only
25        workspace_quality  International Dataset only
11  late_night_device_usage  Supported on both datasets
5           deep_work_hours  Supported on both datasets
4         daily_screen_time  Supported on both datasets
14         motivation_level  Supported on both datasets
15       notification_count  Supported on both datasets
3       concentration_score  Supported on both datasets
7    doomscrolling_duration  Supported on both datasets
18              sleep_hours  Supported on both datasets
19            sleep_quality  Supported on both datasets
20       smartphone_unlocks  Supported on both datasets
21       social_media_hours  Supported on both datasets
1      app_switch_frequency  Supported on both datasets
23     task_completion_rate  Supported on both datasets
6     distraction_frequency  Supported on both datasets
9            focus_sessions  Supported on both datasets

Kết quả SHAP Feature Importance cho thấy 15 indicator có vai trò nhất quán trong mô hình dự đoán Digital Burnout của cả hai dataset.

Nhóm indicator này tập trung chủ yếu vào các khía cạnh:

- Digital Exposure: daily_screen_time, doomscrolling_duration, notification_count, smartphone_unlocks, social_media_hours, app_switch_frequency, late_night_device_usage.
- Cognitive Performance: concentration_score, distraction_frequency, focus_sessions, deep_work_hours, task_completion_rate, motivation_level.
- Sleep & Recovery: sleep_hours, sleep_quality.

Điều này cho thấy các hành vi sử dụng thiết bị, khả năng duy trì tập trung, hiệu suất nhận thức và khả năng phục hồi thông qua giấc ngủ là những yếu tố có ảnh hưởng ổn định đến Digital Burnout trong cả hai bối cảnh nghiên cứu.

Bên cạnh đó, 11 indicator chỉ xuất hiện trong SHAP của International Dataset phản ánh sự khác biệt về đặc điểm dữ liệu. Các yếu tố như stress_level, work_satisfaction, meeting_hours, remote_work_days và workspace_quality liên quan nhiều hơn đến môi trường làm việc, phù hợp với đặc điểm của bộ dữ liệu quốc tế.

Kết quả SHAP cung cấp bằng chứng bổ sung cho Feature Validation, giúp xác định các indicator không chỉ có mối liên hệ thống kê mà còn thực sự đóng góp vào quyết định dự đoán của mô hình Machine Learning.

## 3.4 Indicator Consistency Evidence Analysis

Tổng hợp các bằng chứng từ Feature Validation và SHAP Feature Importance nhằm đánh giá mức độ nhất quán của các indicator DBI giữa International Dataset và Vietnam Dataset.

Hai nguồn bằng chứng được kết hợp:

1. Feature Validation

Đánh giá indicator dựa trên:

- Kiểm định thống kê ANOVA.
- Feature Importance từ mô hình Random Forest.

2. SHAP Feature Importance

Đánh giá indicator dựa trên:

- Mức độ đóng góp của indicator vào quyết định dự đoán của mô hình.
- Khả năng được mô hình sử dụng trong quá trình dự đoán Digital Burnout.

Dựa trên hai nguồn bằng chứng, indicator được phân loại thành các nhóm:

- Strong Evidence: Indicator được validation và được SHAP hỗ trợ trên cả hai dataset.
- Dataset-specific Evidence: Indicator chỉ được hỗ trợ trong một dataset cụ thể.
- Limited Evidence: Indicator chưa có đủ bằng chứng từ validation hoặc SHAP.

In [57]:
# Chuẩn bị bảng Feature Validation cho phân tích consistency

feature_consistency = (
    feature_validation_comparison[
        [
            "indicator",
            "international_validated",
            "vietnam_validated"
        ]
    ]
    .copy()
)


# Chuẩn bị bảng SHAP Consistency

shap_consistency = (
    shap_comparison[
        [
            "indicator",
            "shap_consistency_status"
        ]
    ]
    .copy()
)


# Kết hợp Feature Validation và SHAP

indicator_evidence = (
    feature_consistency
    .merge(
        shap_consistency,
        on="indicator",
        how="outer"
    )
)


display(
    indicator_evidence
)

,indicator,international_validated,vietnam_validated,shap_consistency_status
0,age,False,False,International Dataset only
1,app_switch_frequency,False,True,Supported on both datasets
2,caffeine_intake,False,False,International Dataset only
3,concentration_score,False,True,Supported on both datasets
4,daily_screen_time,True,True,Supported on both datasets
5,deep_work_hours,True,True,Supported on both datasets
6,digital_exhaustion,False,True,NaN
7,digital_stress,False,True,NaN
8,distraction_frequency,True,True,Supported on both datasets
9,doomscrolling_duration,True,True,Supported on both datasets
10,emotional_exhaustion,True,True,International Dataset only
11,focus_sessions,True,True,Supported on both datasets
12,internet_stability,False,False,International Dataset only
13,late_night_device_usage,True,True,Supported on both datasets
14,loss_of_interest,False,True,NaN
15,meeting_hours,False,False,International Dataset only
16,mental_fatigue,False,False,International Dataset only
17,motivation_level,False,True,Supported on both datasets
18,notification_count,True,True,Supported on both datasets
19,performance_decline,False,True,NaN
20,physical_activity,True,False,International Dataset only
21,physical_fatigue,False,True,NaN
22,remote_work_days,False,False,International Dataset only
23,sleep_hours,True,True,Supported on both datasets
24,sleep_quality,False,True,Supported on both datasets
25,smartphone_unlocks,False,True,Supported on both datasets
26,social_media_hours,False,True,Supported on both datasets
27,stress_level,True,False,International Dataset only
28,task_completion_rate,False,True,Supported on both datasets
29,work_satisfaction,True,False,International Dataset only
30,workspace_quality,False,False,International Dataset only

In [58]:
# Điền trạng thái SHAP bị thiếu

indicator_evidence[
    "shap_consistency_status"
] = (
    indicator_evidence[
        "shap_consistency_status"
    ]
    .fillna(
        "Vietnam Dataset only"
    )
)


display(
    indicator_evidence
)

,indicator,international_validated,vietnam_validated,shap_consistency_status
0,age,False,False,International Dataset only
1,app_switch_frequency,False,True,Supported on both datasets
2,caffeine_intake,False,False,International Dataset only
3,concentration_score,False,True,Supported on both datasets
4,daily_screen_time,True,True,Supported on both datasets
5,deep_work_hours,True,True,Supported on both datasets
6,digital_exhaustion,False,True,Vietnam Dataset only
7,digital_stress,False,True,Vietnam Dataset only
8,distraction_frequency,True,True,Supported on both datasets
9,doomscrolling_duration,True,True,Supported on both datasets
10,emotional_exhaustion,True,True,International Dataset only
11,focus_sessions,True,True,Supported on both datasets
12,internet_stability,False,False,International Dataset only
13,late_night_device_usage,True,True,Supported on both datasets
14,loss_of_interest,False,True,Vietnam Dataset only
15,meeting_hours,False,False,International Dataset only
16,mental_fatigue,False,False,International Dataset only
17,motivation_level,False,True,Supported on both datasets
18,notification_count,True,True,Supported on both datasets
19,performance_decline,False,True,Vietnam Dataset only
20,physical_activity,True,False,International Dataset only
21,physical_fatigue,False,True,Vietnam Dataset only
22,remote_work_days,False,False,International Dataset only
23,sleep_hours,True,True,Supported on both datasets
24,sleep_quality,False,True,Supported on both datasets
25,smartphone_unlocks,False,True,Supported on both datasets
26,social_media_hours,False,True,Supported on both datasets
27,stress_level,True,False,International Dataset only
28,task_completion_rate,False,True,Supported on both datasets
29,work_satisfaction,True,False,International Dataset only
30,workspace_quality,False,False,International Dataset only

In [59]:
# Xác định mức độ bằng chứng tổng hợp

def assign_evidence_level(row):

    validation_both = (
        row["international_validated"]
        and
        row["vietnam_validated"]
    )


    shap_both = (
        row["shap_consistency_status"]
        ==
        "Supported on both datasets"
    )


    validation_any = (
        row["international_validated"]
        or
        row["vietnam_validated"]
    )


    shap_any = (
        row["shap_consistency_status"]
        in
        [
            "Supported on both datasets",
            "International Dataset only",
            "Vietnam Dataset only"
        ]
    )


    if validation_both and shap_both:
        return "Strong Evidence"


    elif validation_any and shap_any:
        return "Moderate Evidence"


    elif shap_any or validation_any:
        return "Dataset-specific Evidence"


    else:
        return "Limited Evidence"



indicator_evidence[
    "evidence_level"
] = (
    indicator_evidence.apply(
        assign_evidence_level,
        axis=1
    )
)


display(
    indicator_evidence
)

,indicator,international_validated,vietnam_validated,shap_consistency_status,evidence_level
0,age,False,False,International Dataset only,Dataset-specific Evidence
1,app_switch_frequency,False,True,Supported on both datasets,Moderate Evidence
2,caffeine_intake,False,False,International Dataset only,Dataset-specific Evidence
3,concentration_score,False,True,Supported on both datasets,Moderate Evidence
4,daily_screen_time,True,True,Supported on both datasets,Strong Evidence
5,deep_work_hours,True,True,Supported on both datasets,Strong Evidence
6,digital_exhaustion,False,True,Vietnam Dataset only,Moderate Evidence
7,digital_stress,False,True,Vietnam Dataset only,Moderate Evidence
8,distraction_frequency,True,True,Supported on both datasets,Strong Evidence
9,doomscrolling_duration,True,True,Supported on both datasets,Strong Evidence
10,emotional_exhaustion,True,True,International Dataset only,Moderate Evidence
11,focus_sessions,True,True,Supported on both datasets,Strong Evidence
12,internet_stability,False,False,International Dataset only,Dataset-specific Evidence
13,late_night_device_usage,True,True,Supported on both datasets,Strong Evidence
14,loss_of_interest,False,True,Vietnam Dataset only,Moderate Evidence
15,meeting_hours,False,False,International Dataset only,Dataset-specific Evidence
16,mental_fatigue,False,False,International Dataset only,Dataset-specific Evidence
17,motivation_level,False,True,Supported on both datasets,Moderate Evidence
18,notification_count,True,True,Supported on both datasets,Strong Evidence
19,performance_decline,False,True,Vietnam Dataset only,Moderate Evidence
20,physical_activity,True,False,International Dataset only,Moderate Evidence
21,physical_fatigue,False,True,Vietnam Dataset only,Moderate Evidence
22,remote_work_days,False,False,International Dataset only,Dataset-specific Evidence
23,sleep_hours,True,True,Supported on both datasets,Strong Evidence
24,sleep_quality,False,True,Supported on both datasets,Moderate Evidence
25,smartphone_unlocks,False,True,Supported on both datasets,Moderate Evidence
26,social_media_hours,False,True,Supported on both datasets,Moderate Evidence
27,stress_level,True,False,International Dataset only,Moderate Evidence
28,task_completion_rate,False,True,Supported on both datasets,Moderate Evidence
29,work_satisfaction,True,False,International Dataset only,Moderate Evidence
30,workspace_quality,False,False,International Dataset only,Dataset-specific Evidence

In [60]:
# Thống kê mức độ bằng chứng của indicator

evidence_summary = (
    indicator_evidence[
        "evidence_level"
    ]
    .value_counts()
    .reset_index()
)


evidence_summary.columns = [
    "evidence_level",
    "indicator_count"
]


display(
    evidence_summary
)

              evidence_level  indicator_count
0          Moderate Evidence               16
1            Strong Evidence                8
2  Dataset-specific Evidence                7

Kết quả tổng hợp bằng chứng cho thấy các indicator trong DBI Framework có mức độ nhất quán khác nhau khi được đánh giá trên hai bộ dữ liệu.

Trong tổng số indicator được phân tích, có 8 indicator đạt mức Strong Evidence. Đây là nhóm indicator có độ tin cậy cao nhất khi vừa được xác nhận thông qua Feature Validation vừa được mô hình Machine Learning sử dụng ổn định trên cả hai dataset theo kết quả SHAP.

Bên cạnh đó, 16 indicator thuộc nhóm Moderate Evidence cho thấy có mức độ hỗ trợ đáng kể nhưng chưa hoàn toàn nhất quán giữa hai nguồn dữ liệu. Sự khác biệt này có thể xuất phát từ đặc điểm mẫu nghiên cứu, cấu trúc dữ liệu hoặc bối cảnh sử dụng thiết bị khác nhau giữa International Dataset và Vietnam Dataset.

Nhóm Dataset-specific Evidence gồm 7 indicator phản ánh các yếu tố đặc thù của từng bộ dữ liệu. Các indicator này vẫn có giá trị trong phân tích Digital Burnout nhưng cần được xem xét trong phạm vi bối cảnh dữ liệu cụ thể thay vì áp dụng như các yếu tố chung.

Kết quả Evidence Analysis cung cấp cơ sở định lượng để đánh giá mức độ ổn định của DBI Indicator Framework trước khi thực hiện bước tổng hợp và đối chiếu với bộ chỉ số DBI cuối cùng.

# 4. Final DBI Framework Comparison

Đánh giá mức độ phù hợp của DBI Framework cuối cùng thông qua việc đối chiếu các indicator đã được lựa chọn trong quá trình DBI Refinement với kết quả phân tích trên International Dataset và Vietnam Dataset.

DBI Framework cuối cùng được xây dựng dựa trên 31 indicator ban đầu, trong đó:

- Core Indicator: nhóm indicator có tính tổng quát cao, xuất hiện trong framework chính.
- Dataset-specific Indicator: nhóm indicator phản ánh đặc điểm riêng của từng nhóm dữ liệu.

Kết quả từ Comparative Analysis được sử dụng để đánh giá lại mức độ hỗ trợ của từng indicator thông qua:

- Feature Validation.
- SHAP Feature Importance.
- Evidence Consistency Level.

Mục tiêu của bước này là xác định:

- Indicator nào có bằng chứng mạnh và ổn định.
- Indicator nào phù hợp cho framework chung.
- Indicator nào nên được giữ lại dưới dạng đặc thù dataset.

In [66]:
# Đọc DBI Framework cuối cùng

final_dbi_framework = pd.read_csv(
    os.path.join(
        project_path,
        "data",
        "final",
        "final_dbi_framework.csv"
    )
)


# Hiển thị framework

display(
    final_dbi_framework.head()
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator
1,stress_level,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
2,mental_fatigue,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator
3,digital_exhaustion,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator
4,digital_stress,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator

In [67]:
# Kết hợp Final DBI Framework với Evidence Level

final_dbi_evaluation = (
    final_dbi_framework
    .merge(
        indicator_evidence[
            [
                "indicator",
                "evidence_level",
                "shap_consistency_status"
            ]
        ],
        on="indicator",
        how="left"
    )
)


display(
    final_dbi_evaluation
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority,evidence_level,shap_consistency_status
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator,Moderate Evidence,International Dataset only
1,stress_level,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only
2,mental_fatigue,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
3,digital_exhaustion,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only
4,digital_stress,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only
5,loss_of_interest,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only
6,daily_screen_time,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
7,social_media_hours,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
8,doomscrolling_duration,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
9,late_night_device_usage,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
10,notification_count,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
11,smartphone_unlocks,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
12,app_switch_frequency,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
13,meeting_hours,Digital Exposure,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
14,concentration_score,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
15,distraction_frequency,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
16,focus_sessions,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
17,deep_work_hours,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
18,task_completion_rate,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
19,motivation_level,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
20,performance_decline,Cognitive Performance,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only
21,work_satisfaction,Cognitive Performance,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only
22,sleep_hours,Sleep & Recovery,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets
23,sleep_quality,Sleep & Recovery,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets
24,physical_activity,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only
25,physical_fatigue,Sleep & Recovery,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only
26,caffeine_intake,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
27,age,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
28,workspace_quality,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
29,internet_stability,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only
30,remote_work_days,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only

In [68]:
# Phân loại mức độ bằng chứng cuối cùng của indicator

def assign_final_status(row):

    if row["evidence_level"] == "Strong Evidence":
        return "Core DBI Evidence"

    elif row["evidence_level"] == "Moderate Evidence":
        return "Supporting DBI Indicator"

    elif row["evidence_level"] == "Dataset-specific Evidence":
        return "Dataset-specific Indicator"

    else:
        return "Review"


final_dbi_evaluation[
    "final_status"
] = (
    final_dbi_evaluation.apply(
        assign_final_status,
        axis=1
    )
)


display(
    final_dbi_evaluation
)

,indicator,dbi_dimension,coverage,international_validation,vietnam_validation,international_shap,vietnam_shap,indicator_priority,evidence_level,shap_consistency_status,final_status
0,emotional_exhaustion,Psychological Symptoms,Common,True,True,True,False,Core Indicator,Moderate Evidence,International Dataset only,Supporting DBI Indicator
1,stress_level,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only,Supporting DBI Indicator
2,mental_fatigue,Psychological Symptoms,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
3,digital_exhaustion,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only,Supporting DBI Indicator
4,digital_stress,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only,Supporting DBI Indicator
5,loss_of_interest,Psychological Symptoms,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only,Supporting DBI Indicator
6,daily_screen_time,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
7,social_media_hours,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
8,doomscrolling_duration,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
9,late_night_device_usage,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
10,notification_count,Digital Exposure,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
11,smartphone_unlocks,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
12,app_switch_frequency,Digital Exposure,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
13,meeting_hours,Digital Exposure,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
14,concentration_score,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
15,distraction_frequency,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
16,focus_sessions,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
17,deep_work_hours,Cognitive Performance,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
18,task_completion_rate,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
19,motivation_level,Cognitive Performance,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
20,performance_decline,Cognitive Performance,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only,Supporting DBI Indicator
21,work_satisfaction,Cognitive Performance,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only,Supporting DBI Indicator
22,sleep_hours,Sleep & Recovery,Common,True,True,True,True,Core Indicator,Strong Evidence,Supported on both datasets,Core DBI Evidence
23,sleep_quality,Sleep & Recovery,Common,True,True,True,True,Core Indicator,Moderate Evidence,Supported on both datasets,Supporting DBI Indicator
24,physical_activity,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator,Moderate Evidence,International Dataset only,Supporting DBI Indicator
25,physical_fatigue,Sleep & Recovery,Vietnam Only,False,True,False,False,Dataset-specific Indicator,Moderate Evidence,Vietnam Dataset only,Supporting DBI Indicator
26,caffeine_intake,Sleep & Recovery,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
27,age,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
28,workspace_quality,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
29,internet_stability,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator
30,remote_work_days,Context Variables,International Only,True,False,True,False,Dataset-specific Indicator,Dataset-specific Evidence,International Dataset only,Dataset-specific Indicator

In [69]:
# Tổng hợp mức độ bằng chứng của Final DBI Framework

final_status_summary = (
    final_dbi_evaluation[
        "final_status"
    ]
    .value_counts()
    .reset_index()
)


final_status_summary.columns = [
    "final_status",
    "indicator_count"
]


display(
    final_status_summary
)

                 final_status  indicator_count
0    Supporting DBI Indicator               16
1           Core DBI Evidence                8
2  Dataset-specific Indicator                7

Kết quả Final DBI Framework Comparison cho thấy toàn bộ 31 indicators trong DBI Framework đều nhận được mức độ bằng chứng hỗ trợ khác nhau từ quá trình Comparative Analysis.

Trong đó, 8 indicators đạt mức Core DBI Evidence, thể hiện mức độ nhất quán cao nhất khi đồng thời được hỗ trợ bởi Feature Validation và SHAP Feature Importance trên hai bộ dữ liệu.

16 indicators thuộc nhóm Supporting DBI Indicator vẫn có bằng chứng thực nghiệm đáng kể và đóng vai trò bổ sung trong việc mô tả các khía cạnh khác nhau của Digital Burnout.

7 indicators thuộc nhóm Dataset-specific Indicator phản ánh các yếu tố phụ thuộc vào đặc điểm riêng của International Dataset hoặc Vietnam Dataset. Các indicator này vẫn được duy trì nhằm đảm bảo khả năng thích ứng của DBI Framework với từng bối cảnh nghiên cứu.

Kết quả này xác nhận rằng Final DBI Framework không chỉ dựa trên cơ sở lý thuyết mà còn được củng cố bằng bằng chứng từ dữ liệu thực nghiệm và mô hình Machine Learning.